import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fixtureRoot,sha256,loadNodeSources} from './sources.mjs';
import {createCaptureSuite,verifyCaptureSuite,runtimePin} from './protocol.mjs';
const manifestPin='6c22ded477ea036c36f84dbe8e87d59458f4660b79de324062de713db8b96336';
export function supplementalCases(api){
 const adjacent=(number,direction)=>{const buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setFloat64(0,number);view.setBigUint64(0,view.getBigUint64(0)+(direction*(number>0?1:-1)>0?1n:-1n));return view.getFloat64(0);};
 const feature=(id,ring)=>api.createTerritorialFeature({id,name:id,entityKind:'general',parentId:'',coverageMode:'explicit',geometry:{type:'Polygon',coordinates:[ring]}}),
  make=(id,features,inspectCoordinate,destination,diagnostic)=>({id:'supp-v1-'+id,features,selectedIds:['A','B'],seedId:'A',move:{nodeKey:api.topologyNodeKey(inspectCoordinate),coordinate:destination},inspectCoordinate,expectedPath:'root',diagnostic,observationOnly:true});
 const cases=[],threshold=7.071067811865474e-8;
 for(const [name,a]of [['below',adjacent(threshold,-1)],['at',threshold],['above',adjacent(threshold,1)],['negative-at',-threshold]]){
  const p=[a,-a];cases.push(make('diagonal-epsilon-'+name,[feature('A',[[-2,-2],[2,2],[-2,2],[-2,-2]]),feature('B',[[-2,-2],[2,-2],[2,2],p,[-2,-2]])],p,[0.1,-0.1],{kind:'diagonal-epsilon',parameter:a,epsilon:1e-7,edge:[[-2,-2],[2,2]],referenceThreshold:threshold}));
 }
 for(const sign of [-1,1])for(const [name,x]of [['below',adjacent(sign*5e-8,-1)],['at',sign*5e-8],['above',adjacent(sign*5e-8,1)]]){
  const p=[x,1];cases.push(make(`half-grid-${sign<0?'negative':'positive'}-${name}`,[feature('A',[[-1,0],[-1e-7,0],p,[-1e-7,2],[-1,2],[-1,0]]),feature('B',[[-1e-7,0],[1,0],[1,2],[-1e-7,2],[-1e-7,0]])],p,[-0.1,1],{kind:'signed-half-grid',value:x,precision:7}));
 }
 for(const delta of [4e-10,4e-8])cases.push(make(`owner-already-destination-${delta===4e-10?'4e-10':'4e-8'}`,[feature('A',[[0,0],[1,0],[1,1],[1,2],[0,2],[0,0]]),feature('B',[[1,0],[2,0],[2,2],[1,2],[1+delta,1],[1,0]])],[1,1],[1+delta,1],{kind:'same-quantized-node-destination-owner',delta,unchangedOwnerId:'B',gestureNoOpTolerance:1e-9}));
 return cases;
}
/** Records actual production topology and actual direct-worker requests separately from the UI gesture. */
export async function runSupplementalCase(loaded,definition){
 const clone=value=>structuredClone(value),api=loaded.api,topology=api.buildBoundaryTopology(clone(definition.features)),
  nodes=[...topology.nodes.values()].map(node=>({...clone(node),ownerIds:[...node.ownerIds]})),
  segments=[...topology.segments.values()].map(segment=>({...clone(segment),ownerIds:[...segment.ownerIds]}));
 const workflow=await loaded.runBoundaryCase(loaded,clone(definition)),requests=[],transport=[],createWorker=()=>{const worker=loaded.createWorker(),adapter={onmessage:null,onerror:null,postMessage(message){transport.push({direction:'request',message:clone(message)});worker.postMessage(message);},terminate:()=>worker.terminate()};worker.onmessage=event=>{transport.push({direction:'response',message:clone(event.data)});adapter.onmessage?.(event);};worker.onerror=error=>adapter.onerror?.(error);return adapter;},client=api.createMapEditWorkerClient({createWorker,getEntities:()=>definition.features,getFeatureById:id=>definition.features.find(f=>f.id===id),getTargetRevision:()=>0});
 const execute=async(operation,payload)=>{const row={operation,payload:clone(payload),status:'pending'};requests.push(row);try{const response=await client.execute(operation,{payload});row.status='resolved';row.response=clone(response);return {observed:true,ok:true,result:clone(response.result)};}catch(error){row.status='rejected';row.error={message:error.message,code:error.code||null,cancelled:error.cancelled===true};return {observed:true,ok:false,error:clone(row.error)};}};
 let directPreparation,directMove;
 try{directPreparation=await execute('boundary-prepare',{targetIds:definition.selectedIds,mode:'border'});directMove=directPreparation.ok?await execute('boundary-move',{preparationId:directPreparation.result.preparationId,nodeKey:definition.move.nodeKey,coordinate:definition.move.coordinate}):{observed:false,reason:'Actual direct preparation failed; no receipt exists for movement.'};}
 finally{client.stop();}
 const changedOwnerIds=directMove.ok?directMove.result.features.filter(feature=>JSON.stringify(feature.geometry)!==JSON.stringify(definition.features.find(f=>f.id===feature.id)?.geometry)).map(feature=>feature.id):[];
 return {case:definition.id,input:clone(definition),topology:{precision:topology.precision,epsilon:topology.epsilon,nodes,segments},inspect:{nodeKey:api.topologyNodeKey(definition.inspectCoordinate),node:nodes.find(node=>node.key===api.topologyNodeKey(definition.inspectCoordinate))||null},workflow,directPreparation,directMove,changedOwnerIds,requests,transport,observationLimits:{rawParity:false,geographicOnly:true,UIAndDirectWorkerAreSeparate:true,classification:'Actual outcomes only; nearby-threshold classifications are not copied from Node discovery.'}};
}
export async function writeSupplementalInputs(){const loaded=await loadNodeSources();try{
 const cases=supplementalCases(loaded.api),bytes=Buffer.from(JSON.stringify({schema:'pando-m974-supplemental-inputs',version:1,cases},null,2)+'\n'),manifest={schema:'pando-m974-supplemental-input-pin',version:1,parentOriginalCorpusCommit:'735ee31149bd7a78e3521d1a498efc96f59352c1',role:'Separate synthetic threshold diagnostics; original68workflow inputs stay immutable.',file:'supplemental-v1-cases.json',bytes:bytes.length,sha256:sha256(bytes),orderedCaseIds:cases.map(c=>c.id)};
 fs.writeFileSync(path.join(fixtureRoot,manifest.file),bytes);fs.writeFileSync(path.join(fixtureRoot,'supplemental-v1-manifest.json'),JSON.stringify(manifest,null,2)+'\n');return {manifestSha256:sha256(JSON.stringify(manifest)),cases:cases.length};
 }finally{loaded.cleanup();}}
export function readSupplementalInputs(){const manifest=JSON.parse(fs.readFileSync(path.join(fixtureRoot,'supplemental-v1-manifest.json')));assert.equal(sha256(JSON.stringify(manifest)),manifestPin,'immutable separate supplemental manifest');const bytes=fs.readFileSync(path.join(fixtureRoot,manifest.file));assert.equal(bytes.length,manifest.bytes);assert.equal(sha256(bytes),manifest.sha256);const input=JSON.parse(bytes);assert.equal(input.schema,'pando-m974-supplemental-inputs');assert.equal(input.version,1);assert.deepEqual(input.cases.map(c=>c.id),manifest.orderedCaseIds);return {manifest,cases:input.cases};}
const hashes=()=>Object.fromEntries(['supplemental.mjs','supplemental-browser-runner.mjs'].map(name=>[name,sha256(fs.readFileSync(new URL(name,import.meta.url)))]));
const identity=suite=>({schema:suite.schema,version:suite.version,commit:suite.base.commit,runId:suite.base.runId,originalCorpusIdentity:suite.base.identity,supplementalManifestSha256:sha256(JSON.stringify(suite.manifest)),casesSha256:sha256(JSON.stringify(suite.cases)),runtimeSha256:suite.runtime.sha256,harnessFiles:suite.harnessFiles});
export async function createSupplementalSuite(options){const base=await createCaptureSuite(options),{manifest,cases}=readSupplementalInputs(),source=`({runSupplementalCase:${runSupplementalCase.toString()}})`,suite={schema:'pando-m974-supplemental-suite',version:1,base,manifest,cases,runtime:{source,sha256:sha256(source)},harnessFiles:hashes()};suite.identity=identity(suite);return suite;}
export function verifySupplementalSuite(suite){assert.equal(suite.schema,'pando-m974-supplemental-suite');assert.equal(suite.version,1);verifyCaptureSuite(suite.base);const pinned=readSupplementalInputs();assert.deepEqual(suite.manifest,pinned.manifest);assert.deepEqual(suite.cases,pinned.cases);assert.equal(suite.runtime.source,`({runSupplementalCase:${runSupplementalCase.toString()}})`);assert.equal(suite.runtime.sha256,sha256(suite.runtime.source));assert.deepEqual(suite.harnessFiles,hashes());assert.deepEqual(suite.identity,identity(suite));return suite;}
export function verifySupplementalReport(suite,report){verifySupplementalSuite(suite);assert.equal(report.schema,'pando-m974-actual-chromium-supplemental');assert.equal(report.version,1);assert.equal(report.state,'complete');assert.deepEqual(report.identity,suite.identity);assert.equal(report.runtime.browserVersion,runtimePin.chromium);assert.equal(report.runtime.chromiumRevision,runtimePin.revision);assert.equal(report.runtime.playwright,runtimePin.playwright);assert.equal(report.runtime.cdp.jsVersion,runtimePin.v8);assert.ok(['Chrome/','HeadlessChrome/'].some(prefix=>report.runtime.cdp.product===prefix+runtimePin.chromium));assert.deepEqual(report.sourceHashes,Object.fromEntries(suite.base.manifest.sources.map(s=>[s.path,s.sha256])));assert.deepEqual(report.cases.map(row=>row.case),suite.cases.map(c=>c.id));
 assert.deepEqual(report.observationLimits,{rawParity:false,geographicOnly:true,originalCorpusUnchanged:true,UIAndDirectWorkerAreSeparate:true});
 for(const [index,row]of report.cases.entries()){
  const definition=suite.cases[index];assert.deepEqual(row.input,definition);assert.deepEqual(row.workflow.input,definition);assert.deepEqual(row.workflow.extractionEvidence,suite.base.boundaryExtraction);assert.ok(row.topology.nodes.length>0&&row.topology.segments.length>0);assert.equal(row.topology.precision,7);assert.equal(row.topology.epsilon,1e-7);
  const ids=new Set(definition.features.map(feature=>feature.id));for(const node of row.topology.nodes){assert.equal(typeof node.key,'string');assert.ok(Array.isArray(node.coordinate));assert.ok(Array.isArray(node.ownerIds)&&node.ownerIds.length>0&&node.ownerIds.every(id=>ids.has(id)));assert.ok(Array.isArray(node.refs)&&Array.isArray(node.virtualRefs));for(const ref of [...node.refs,...node.virtualRefs])assert.ok(ids.has(ref.featureId));}
  for(const segment of row.topology.segments){assert.ok(Array.isArray(segment.ownerIds)&&segment.ownerIds.length>0);assert.ok(Array.isArray(segment.a)&&Array.isArray(segment.b)&&Array.isArray(segment.refs));}
  assert.deepEqual(row.inspect.node,row.topology.nodes.find(node=>node.key===row.inspect.nodeKey)||null);
  for(const key of ['before','cold','pending','settled'])assert.equal(row.workflow.stages[key]?.observed,true,'mandatory supplemental workflow stage');
  for(const name of ['before','cold','pending','prepared','drag','preview','cancel','impactCancel','confirm','undo','redo','settled'])assert.equal(typeof row.workflow.stages[name]?.observed,'boolean','explicit supplemental workflow slot '+name);
  for(const stage of Object.values(row.workflow.stages)){assert.equal(typeof stage.observed,'boolean');if(stage.observed){assert.ok(stage.state?.document);assert.ok(stage.state.history);}else assert.ok(stage.reason);}
  const stages=row.workflow.stages;assert.equal(typeof row.workflow.entry?.ok,'boolean');
  if(row.workflow.entry.ok)assert.equal(stages.prepared.observed,true,'entered workflow must record actual preparation');
  if(stages.prepared.observed&&stages.prepared.outcome.ok){assert.equal(typeof row.workflow.gesture?.ok,'boolean');if(row.workflow.gesture.ok){assert.equal(stages.drag.observed,true);assert.equal(typeof stages.drag.outcome.changed,'boolean');}else assert.equal(stages.drag.observed,false);}
  if(stages.preview.observed){assert.equal(stages.preview.outcome.ok,true);assert.equal(stages.cancel.observed,true);assert.equal(stages.cancel.outcome.ok,true);assert.equal(stages.confirm.observed,true);}
  else for(const name of ['cancel','confirm','undo','redo'])assert.equal(stages[name].observed,false,'unreached preview cannot claim '+name);
  if(stages.confirm.observed&&stages.confirm.outcome.ok){for(const name of ['undo','redo']){assert.equal(stages[name].observed,true);assert.equal(stages[name].outcome.ok,true);}assert.equal(stages.confirm.state.history.undo,stages.before.state.history.undo+1);assert.deepEqual(stages.undo.state.document,stages.before.state.document);assert.deepEqual(stages.redo.state.document,stages.confirm.state.document);}
  for(const name of ['drag','preview','cancel'])if(stages[name].observed)assert.deepEqual(stages[name].state.document,stages.before.state.document,'uncommitted canonical model');
  assert.equal(row.workflow.observationLimits.browserPointerProjection,false);assert.equal(row.workflow.observationLimits.draftUndoRedo,false);
  const sent=row.transport.filter(event=>event.direction==='request'&&event.message.type==='execute');assert.equal(sent.length,row.requests.length,'exact direct worker request count');
  for(const [requestIndex,request]of row.requests.entries()){
   const outgoing=sent[requestIndex].message;assert.equal(outgoing.operation,request.operation);assert.deepEqual(outgoing.payload,request.payload);assert.ok(Number.isInteger(outgoing.requestId));
   const incoming=row.transport.find(event=>event.direction==='response'&&event.message.type==='result'&&event.message.requestId===outgoing.requestId);assert.ok(incoming,'actual direct worker terminal envelope');
   assert.equal(request.status,incoming.message.ok?'resolved':'rejected');if(incoming.message.ok){assert.equal(request.response.requestId,outgoing.requestId);assert.deepEqual(request.response.result,incoming.message.result);}else assert.equal(request.error.message,incoming.message.message);
  }
  assert.equal(row.directPreparation?.observed,true);assert.equal(row.requests[0]?.operation,'boundary-prepare');assert.equal(typeof row.directPreparation.ok,'boolean');
  for(const request of row.requests){assert.ok(['resolved','rejected'].includes(request.status));if(request.status==='resolved'){assert.ok(request.response?.result);const response=row.transport.find(event=>event.direction==='response'&&event.message.type==='result'&&event.message.requestId===request.response.requestId&&event.message.ok===true);assert.ok(response,'actual supplemental worker response required');assert.deepEqual(request.response.result,response.message.result);}else assert.equal(typeof request.error?.message,'string');}
  assert.equal(row.directPreparation.ok,row.requests[0].status==='resolved');assert.deepEqual(row.requests[0].payload,{targetIds:definition.selectedIds,mode:'border'});if(row.directPreparation.ok)assert.deepEqual(row.directPreparation.result,row.requests[0].response.result);else assert.deepEqual(row.directPreparation.error,row.requests[0].error);
  if(row.directPreparation.ok){assert.equal(row.directMove?.observed,true);assert.equal(row.requests[1]?.operation,'boundary-move');assert.equal(typeof row.directMove.ok,'boolean');assert.equal(row.directMove.ok,row.requests[1].status==='resolved');assert.deepEqual(row.requests[1].payload,{preparationId:row.directPreparation.result.preparationId,nodeKey:definition.move.nodeKey,coordinate:definition.move.coordinate});if(!row.directMove.ok)assert.deepEqual(row.directMove.error,row.requests[1].error);}else{assert.equal(row.directMove.observed,false);assert.ok(row.directMove.reason);}
  if(row.directMove.ok)assert.deepEqual(row.directMove.result,row.requests[1].response.result);
  const changed=row.directMove.ok?row.directMove.result.features.filter(feature=>JSON.stringify(feature.geometry)!==JSON.stringify(definition.features.find(original=>original.id===feature.id)?.geometry)).map(feature=>feature.id):[];assert.deepEqual(row.changedOwnerIds,changed,'changed owners derived from retained actual patches');
  assert.equal(row.observationLimits.rawParity,false);assert.equal(row.observationLimits.geographicOnly,true);assert.equal(row.observationLimits.UIAndDirectWorkerAreSeparate,true);
 }
 return report;
}
if(process.argv[2]==='--write-supplemental-inputs')console.log(JSON.stringify(await writeSupplementalInputs()));
