import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('./', import.meta.url));
let oracle = null;
try { oracle = await import('../../../tools/web-v10-exchange-oracle.mjs'); }
catch (error) { if (error.code !== 'ERR_MODULE_NOT_FOUND') throw error; }
test.beforeEach(() => assert.ok(oracle, 'new production Web10 oracle runner is not implemented'));
const json = name => JSON.parse(fs.readFileSync(path.join(root, name)));

// Hand-written synthetic checker input. This is neither a production fixture
// nor an expected file generated by the native codec. The immutable nine-file
// exchange corpus also has nonempty names and absent metadata.nameSource.
test('synthetic nonempty native name is explicit when independent Web metadata has no nameSource', () => {
  const common = { version: 'synthetic-checker-test', savedAt: '2026-10-04T00:00:00.000Z',
    baseDataset: 'external-territorial-entities', landObjectModel: { schemaVersion: 2 },
    territorialModel: { schemaVersion: 6 }, distributionModel: { schemaVersion: 3 },
    sourceInfo: null, physicalSourceInfo: {}, physicalSettings: {} };
  const records = { schemaVersion: 1, lifetimes: [], geometryBindings: [], parentRelations: [] };
  const independentWeb = { ...common, format: 'pandolab-project-state', schemaVersion: 10,
    territorialEntities: [{ type: 'Feature', id: 'synthetic-A', geometry: null,
      properties: { schemaVersion: 6, entityKind: 'general', name: 'Synthetic named territory',
        style: { color: '#507090' }, locked: false, notes: '', metadata: {},
        sourceFolderId: 'synthetic', sourceEntityId: 'source-A', sourceGeometryVersion: '1' } }],
    timelineRecords: records, geometries: [], labels: [], hydroEdits: [], genericFeatures: [],
    distributionLayers: [], distributionEntries: [] };
  const syntheticNative = { format: 'pandoeditor-project', version: 10,
    units: [{ id: 'synthetic-A', kind: 'general', name: 'Synthetic named territory',
      baseName: '', nameExplicit: true, libraryOrigin: null, locked: false, notes: '', metadata: {},
      sourceFolderId: 'synthetic', sourceEntityId: 'source-A', sourceGeometryVersion: '1' }],
    timelineRecords: structuredClone(records), geometries: [],
    presentation: { objectStyles: { territorial: { 'synthetic-A': { color: '#507090', opacity: 1 } } } },
    content: { countryDetails: [], symbols: [], labels: [], hydro: [], genericFeatures: [],
      distributionLayers: [], distributionEntries: [] }, extensions: [], exchangeMetadata: structuredClone(common) };
  oracle.compareNativeStorage(syntheticNative, independentWeb, 'synthetic named native');
  const changed = structuredClone(syntheticNative); changed.units[0].nameExplicit = false;
  assert.throws(() => oracle.compareNativeStorage(changed, independentWeb, 'synthetic flag loss'), /nameExplicit/);
});

test('the fixed source snapshot and nine independent inputs have exact pinned bytes', () => {
  const result = oracle.verifyFixtureSnapshot(root);
  assert.equal(result.sourceCommit, 'ebcfae4d27b29cbbea6416a7045a4806930204be');
  assert.equal(result.inputFileCount, 9);
  assert.equal(result.sourceFileCount, 30);
});
test('sourceEntityId and coordinate changes fail the literal expected oracle', () => {
  const expected = json('static.expected.json');
  for (const modify of [p => p.territorialEntities[0].properties.sourceEntityId = 'wrong',
                        p => p.geometries.find(row => row.id === 'shape' && row.version === 1).geojson.coordinates[0][0][0][0] += 0.000000000001]) {
    const project = json('static.json'); modify(project);
    assert.throws(() => oracle.compareProject(project, expected, 'mutated input'));
  }
});
test('evidence is created beneath the complete requested directory', async () => {
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'web10-evidence-'));
  try {
    const evidenceDir = path.join(temporary, 'new-parent', 'new-child');
    const report = await oracle.runWebOracle({ fixtureRoot: root, evidenceDir });
    assert.ok(report.evidenceDir.startsWith(evidenceDir + path.sep));
    assert.equal(JSON.parse(fs.readFileSync(path.join(report.evidenceDir, 'results.json'))).pass, 10);
  } finally { fs.rmSync(temporary, { recursive: true, force: true }); }
});
test('only identity/archive/record collection order is immaterial', () => {
  const project = json('static.json'), expected = json('static.expected.json');
  project.territorialEntities.reverse(); project.geometries.reverse();
  for (const key of ['lifetimes', 'geometryBindings', 'parentRelations']) project.timelineRecords[key].reverse();
  oracle.compareProject(project, expected, 'row order');
  project.geometries.pop();
  assert.throws(() => oracle.compareProject(project, expected, 'missing unreferenced archive'));
});
test('retired project/model numbers are rejected before comparison', () => {
  for (const modify of [p => p.schemaVersion = 9, p => p.territorialModel.schemaVersion = 5]) {
    const project = json('static.json'); modify(project);
    assert.throws(() => oracle.compareProject(project, json('static.expected.json'), 'retired header'));
  }
});
test('a changed source file is rejected without trusting an edited sidecar', () => {
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'web10-integrity-'));
  try {
    fs.cpSync(root, temporary, { recursive: true });
    const source = path.join(temporary, 'source/assets/js/modules/project-serializer.js');
    fs.appendFileSync(source, '\n// changed source\n');
    assert.throws(() => oracle.verifyFixtureSnapshot(temporary));
    const manifestPath = path.join(temporary, 'source-manifest.json');
    const manifest = JSON.parse(fs.readFileSync(manifestPath)); manifest.sources = [];
    fs.writeFileSync(manifestPath, JSON.stringify(manifest));
    assert.throws(() => oracle.verifyFixtureSnapshot(temporary));
  } finally { fs.rmSync(temporary, { recursive: true, force: true }); }
});
test('actual fixed production serializer and SQL WASM Worker round-trip all six file routes', async () => {
  const report = await oracle.runWebOracle({ fixtureRoot: root });
  assert.equal(report.sourceCommit, 'ebcfae4d27b29cbbea6416a7045a4806930204be');
  assert.equal(report.pass, 10); assert.equal(report.fail, 0); assert.equal(report.skip, 0);
  assert.equal(report.nativeExecuted, false);
  assert.equal(report.cases[0].inputFileSha256, '4eb296c89212a454ef088d561be88835c2bd00c561dc2bf5c3afaba90da4e9b2');
  assert.equal(report.cases[1].inputFileSha256, 'b4e2e73f9f437416b1379145475970ba94454c14fb2671107cdbc2801ea17fd1');
  assert.deepEqual(report.cases.filter(row => row.kind).map(row => row.name), [
    'static-json', 'static-gpkg', 'complex-json', 'complex-gpkg', 'calendar-boundaries-json', 'calendar-boundaries-gpkg']);
});
test('the trace contract requires every real file boundary and checks the native header', () => {
  assert.deepEqual(oracle.TRACE_FILES, ['read.web.json', 'saved.native.json', 'reopened.web.json',
    'saved.native.gpkg', 'package-reopened.web.json', 'export.web.json', 'activation.json', 'trace-status.json']);
  assert.throws(() => oracle.compareNativeStorage(json('static.json'), json('static.json'), 'web is not native'), /native format/);
});
test('native exchange common fields remain literal while only contract row ordering varies', () => {
  const input = json('static.json'), output = structuredClone(input);
  output.territorialEntities.reverse(); output.geometries.reverse();
  oracle.compareFullWebProject(output, input, 'permitted rows');
  output.physicalSourceInfo.terrain.dataset = 'changed';
  assert.throws(() => oracle.compareFullWebProject(output, input, 'source loss'), /physicalSourceInfo/);
});
test('Web-only evidence explicitly excludes native traces and lists actual Worker stages', async () => {
  const report = await oracle.runWebOracle({ fixtureRoot: root });
  assert.deepEqual(report.processes, []);
  assert.equal(report.directions['web-only'].processed, 6);
  assert.equal(report.directions['web-app-web'].processed, 0);
  assert.equal(report.directions['app-web-app'].processed, 0);
  assert.equal(report.traceCount, 0);
  assert.equal(report.mismatch, 0);
  assert.ok(report.cases[0].stages.some(stage => stage.stage === 'web.worker.read' && stage.passed));
});
test('raw output source IDs and endpoint spellings reject before the actual Web reader can normalize them', async () => {
  const api = await import('./source/assets/js/modules/project-state.js');
  const fixed = json('calendar-boundaries.json'), expected = json('calendar-boundaries.expected.json');
  for (const modify of [p => p.territorialEntities[0].properties.sourceEntityId = ' timeline-test ',
    p => p.timelineRecords.geometryBindings.find(row => row.id === 'A:new').validFrom = ' +12000-02-29 ']) {
    const output = structuredClone(fixed); modify(output);
    // Demonstrate the actual production reader masks this raw output mutation.
    oracle.compareFullWebProject(api.prepareProjectForStorage(output), api.prepareProjectForStorage(fixed), 'reader-normalized');
    assert.throws(() => oracle.checkWeb(api, output, expected, fixed, 'app.raw-output'), /raw/);
  }
});
