#include <pandoeditor/map/sharedboundary.h>
#include "territorialgeometry.h"
#include "territorial_fixture.h"
#include "projectcodec.h"
#include <QtTest>
#include <QFile>
#include <QFileInfo>
#include <QDir>
#include <QSet>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <zlib.h>
#include <algorithm>
using namespace pandoeditor;
namespace {
Geometry decode(const QJsonObject& value){Geometry geometry;geometry.type=value["type"].toString().toStdString();auto polygons=value["coordinates"].toArray();if(geometry.type=="Polygon"){QJsonArray wrapped;wrapped.append(polygons);polygons=wrapped;}for(const auto& polygon:polygons){Polygon rings;for(const auto& ring:polygon.toArray()){Ring points;for(const auto& point:ring.toArray()){const auto xy=point.toArray();points.push_back({xy[0].toDouble(),xy[1].toDouble()});}rings.push_back(std::move(points));}geometry.polygons.push_back(std::move(rings));}return geometry;}
QJsonObject encode(const Geometry& geometry){QJsonArray polygons;for(const auto& polygon:geometry.polygons){QJsonArray rings;for(const auto& ring:polygon){QJsonArray points;for(auto point:ring)points.append(QJsonArray{point.x,point.y});rings.append(points);}polygons.append(rings);}return {{"type",QString::fromStdString(geometry.type)},{"coordinates",geometry.type=="Polygon"?QJsonValue(polygons.first()):QJsonValue(polygons)}};}
QJsonArray names(const std::vector<std::string>& values){QJsonArray rows;for(const auto& value:values)rows.append(QString::fromStdString(value));return rows;}
QJsonArray references(const std::vector<sharedboundary::Reference>& values,bool virtualRef){QJsonArray rows;for(const auto& value:values){QJsonObject row{{"featureId",QString::fromStdString(value.owner)},{"polygonIndex",double(value.polygon)},{"ringIndex",double(value.ring)}};if(virtualRef){row["segmentIndex"]=double(value.index);row["t"]=value.t;}else row["vertexIndex"]=double(value.index);rows.append(row);}return rows;}
ProjectDocument fixture(const QJsonObject& definition){ProjectDocument document;document.documentId="m974-supplemental-browser-regression";for(const auto& value:definition["features"].toArray()){const auto feature=value.toObject(),properties=feature["properties"].toObject();const auto id=feature["id"].toString().toStdString();const GeometryRef ref{id,1};document.geometries.insert(ref,decode(feature["geometry"].toObject()));appendTerritory(document,{id,properties["name"].toString().toStdString(),"",UnitKind::General,properties["locked"].toBool()},ref,properties["parentId"].toString().toStdString(),properties["coverageMode"].toString().toStdString());document.presentation.objectStyles[territorialRef(id)]={};}return document;}
}
class M974BoundarySupplementalTests:public QObject {
    Q_OBJECT
private slots:
    void actualBrowserTopologyAndGesture_data(){
        QTest::addColumn<QJsonObject>("observed");const auto directory=QFileInfo(QString::fromUtf8(__FILE__)).dir();
        QFile manifestFile(directory.filePath("fixtures/web-m974/supplemental-v1-observations.json.manifest.json"));QVERIFY(manifestFile.open(QIODevice::ReadOnly));const auto manifest=QJsonDocument::fromJson(manifestFile.readAll()).object();QCOMPARE(manifest["captureCommit"].toString(),QString("17014e61ad0059dc9a55a8a1e7ce150e4ae6d5e1"));QCOMPARE(manifest["captureRunId"].toString(),QString("37291915880"));QCOMPARE(manifest["browserReportSha256"].toString(),QString("864b22071d98606b5e6fbb40cd3e8008b1dbd70b31e4b626a7129ca37529e45d"));
        QFile file(directory.filePath("fixtures/web-m974/supplemental-v1-observations.json.gz"));QVERIFY(file.open(QIODevice::ReadOnly));auto compressed=file.readAll();QCOMPARE(compressed.size(),37307);QCOMPARE(QCryptographicHash::hash(compressed,QCryptographicHash::Sha256).toHex(),QByteArray("88075d3f7f5ab24314891042c1d4ce8d384e00e185874ee0620da5524844983b"));
        z_stream stream{};stream.next_in=reinterpret_cast<Bytef*>(compressed.data());stream.avail_in=uInt(compressed.size());QCOMPARE(inflateInit2(&stream,16+MAX_WBITS),Z_OK);QByteArray bytes;int status=Z_OK;while(status==Z_OK){const auto offset=bytes.size();bytes.resize(offset+16384);stream.next_out=reinterpret_cast<Bytef*>(bytes.data()+offset);stream.avail_out=16384;status=inflate(&stream,Z_NO_FLUSH);bytes.resize(offset+16384-stream.avail_out);}inflateEnd(&stream);QCOMPARE(status,Z_STREAM_END);QCOMPARE(bytes.size(),671190);QCOMPARE(QCryptographicHash::hash(bytes,QCryptographicHash::Sha256).toHex(),QByteArray("c4f79b832dba4d9aed401a36292fb4c9a079ea3fd92c901a4fdf81eccc2f1c81"));
        QFile inputFile(directory.filePath("fixtures/web-m974/supplemental-v1-cases.json"));QVERIFY(inputFile.open(QIODevice::ReadOnly));const auto inputs=QJsonDocument::fromJson(inputFile.readAll()).object()["cases"].toArray();const auto rows=QJsonDocument::fromJson(bytes).array();QCOMPARE(rows.size(),12);QCOMPARE(inputs.size(),rows.size());QSet<QString> ids;
        for(int i=0;i<rows.size();++i){const auto row=rows[i].toObject();const auto id=row["case"].toString();QVERIFY(!ids.contains(id));ids.insert(id);QCOMPARE(row["input"].toObject(),inputs[i].toObject());QVERIFY(!row["observationLimits"].toObject()["rawParity"].toBool());QVERIFY(row["observationLimits"].toObject()["UIAndDirectWorkerAreSeparate"].toBool());QTest::newRow(qPrintable(id))<<row;}
    }
    void actualBrowserTopologyAndGesture(){
        QFETCH(QJsonObject,observed);const auto input=observed["input"].toObject();Project project;project.replace(fixture(input));const auto before=projectcodec::encode(project);std::vector<ObjectRef> owners;for(const auto& id:input["selectedIds"].toArray())owners.push_back(territorialRef(id.toString().toStdString()));auto session=sharedboundary::Session::prepare(project.document(),project.index(),owners);const auto preparation=observed["directPreparation"].toObject()["result"].toObject();QCOMPARE(session->valid(),preparation["valid"].toBool());QCOMPARE(QString::fromStdString(sharedboundary::nodeKeyText({input["inspectCoordinate"].toArray()[0].toDouble(),input["inspectCoordinate"].toArray()[1].toDouble()})),observed["inspect"].toObject()["nodeKey"].toString());
        const auto handles=preparation["handles"].toArray();QCOMPARE(session->nodes().size(),std::size_t(handles.size()));for(std::size_t i=0;i<session->nodes().size();++i){const auto& node=session->nodes()[i];const auto expected=handles[int(i)].toObject();QCOMPARE(QString::fromStdString(sharedboundary::nodeKeyText(node.coordinate)),expected["nodeKey"].toString());QCOMPARE((QJsonArray{node.coordinate.x,node.coordinate.y}),expected["coordinate"].toArray());QCOMPARE(names(node.owners),expected["ownerIds"].toArray());QCOMPARE(references(node.refs,false),expected["refs"].toArray());QCOMPARE(references(node.virtualRefs,true),expected["virtualRefs"].toArray());QCOMPARE(node.fixed,expected["fixed"].toBool());QJsonArray incident;for(const auto& segment:node.incidentSegments)incident.append(QJsonObject{{"start",QJsonArray{segment.first.x,segment.first.y}},{"end",QJsonArray{segment.second.x,segment.second.y}}});QCOMPARE(incident,expected["segments"].toArray());}
        const auto segments=preparation["segments"].toArray();QCOMPARE(session->segments().size(),std::size_t(segments.size()));for(std::size_t i=0;i<session->segments().size();++i){const auto& segment=session->segments()[i];const auto a=session->nodes()[segment.start].coordinate,b=session->nodes()[segment.end].coordinate;const auto left=sharedboundary::nodeKeyText(a),right=sharedboundary::nodeKeyText(b);const auto expected=segments[int(i)].toObject();QCOMPARE(QString::fromStdString(left<right?left+"|"+right:right+"|"+left),expected["key"].toString());QCOMPARE((QJsonArray{a.x,a.y}),expected["start"].toArray());QCOMPARE((QJsonArray{b.x,b.y}),expected["end"].toArray());}
        const auto stages=observed["workflow"].toObject()["stages"].toObject();const auto gesture=stages["drag"].toObject();const auto movement=input["move"].toObject();const auto found=std::find_if(session->nodes().begin(),session->nodes().end(),[&](const auto& node){return QString::fromStdString(sharedboundary::nodeKeyText(node.coordinate))==movement["nodeKey"].toString();});const bool movable=found!=session->nodes().end()&&session->canMove(std::size_t(found-session->nodes().begin()));QCOMPARE(movable,gesture["observed"].toBool());if(!movable){QCOMPARE(projectcodec::encode(project),before);return;}
        const auto coordinate=movement["coordinate"].toArray();const auto index=std::size_t(found-session->nodes().begin());QVERIFY(session->beginDrag(index));const bool changed=session->move(index,{coordinate[0].toDouble(),coordinate[1].toDouble()});QCOMPARE(changed,gesture["outcome"].toObject()["changed"].toBool());QVERIFY(session->changedDrafts().empty());QCOMPARE(session->endDrag(false),changed);QCOMPARE(projectcodec::encode(project),before);
        // 4e-10 is a real gesture no-op. Its separately observed raw worker
        // patch is deliberately not presented as a native gesture result.
        if(!changed){QVERIFY(session->changedDrafts().empty());QVERIFY(!session->canUndo());QVERIFY(!stages["preview"].toObject()["observed"].toBool());return;}
        const auto direct=observed["directMove"].toObject();QVERIFY(direct["ok"].toBool());const auto expected=direct["result"].toObject()["features"].toArray();const auto patches=session->changedDrafts();QCOMPARE(patches.size(),std::size_t(expected.size()));QJsonArray affected,actuallyChanged;for(std::size_t i=0;i<patches.size();++i){const auto id=QString::fromStdString(patches[i].owner.id);affected.append(id);QCOMPARE(id,expected[int(i)].toObject()["id"].toString());QCOMPARE(encode(patches[i].geometry),expected[int(i)].toObject()["geometry"].toObject());const auto original=project.document().geometries.get(staticGeometryBinding(project.document(),patches[i].owner.id).geometryRef);if(encode(patches[i].geometry)!=encode(*original))actuallyChanged.append(id);}QCOMPARE(affected,direct["result"].toObject()["affectedIds"].toArray());QCOMPARE(actuallyChanged,observed["changedOwnerIds"].toArray());
        JobScheduler jobs;const auto ticket=jobs.enqueue(project.snapshot(),"supplemental-boundary");jobs.takeNext();const auto receipt=calculateBoundaryGeometryPreview(project.snapshot(),SharedBoundaryIntent{patches},ticket.token());const bool previewObserved=stages["preview"].toObject()["observed"].toBool();QCOMPARE(receipt.ok(),previewObserved);QCOMPARE(projectcodec::encode(project),before);
    }
};
QTEST_MAIN(M974BoundarySupplementalTests)
#include "m974_boundary_supplemental_tests.moc"
