#include "territorial_fixture.h"
#include "editorcontroller.h"
#include "river_controller_fixture.h"
#include <QtTest>
#include <QFile>
#include <QTemporaryDir>
#include <QDirIterator>
#include <QStandardPaths>
#include <QThreadPool>
#include <thread>
using namespace pandoeditor;
using river_controller_fixture::FixtureCopy;
class RiverSelectionControllerTests:public QObject {
 Q_OBJECT
static QUrl writeProject(const QString& path,int donors=1,double left=80,double bottom=30,const QString& manifest={}) {
 ProjectDocument d;d.documentId="river-cache-fixture";
 const auto add=[&](const std::string& id,double x){Geometry g;g.type="Polygon";g.polygons={{{{x,bottom},{x+.1,bottom},{x+.1,bottom+.1},{x,bottom+.1},{x,bottom}}}};GeometryRef r{id,1};d.geometries.insert(r,g);appendTerritory(d,{id,id,"",UnitKind::General,false},r);d.presentation.objectStyles[territorialRef(id)]={};};
 add("target",left-10);for(int i=0;i<donors;++i)add("donor"+std::to_string(i),left+i*.2);
 d.physicalData.source=manifest.isEmpty()?std::string(WEB_HYDRO_FIXTURE)+"/v0.13.1/manifest.json":manifest.toStdString();Project p;p.replace(d);QFile f(path);if(!f.open(QIODevice::WriteOnly))throw std::runtime_error("write");f.write(projectcodec::encode(p));return QUrl::fromLocalFile(path);
}
static void changeProject(const QUrl& url,const std::function<void(ProjectDocument&)>& change) {
 auto document=projectcodec::decode(river_controller_fixture::read(url.toLocalFile()));change(document);Project project;project.replace(std::move(document));river_controller_fixture::write(url.toLocalFile(),projectcodec::encode(project));
}
static bool advanceComponents(EditorController& controller) {
 return QTest::qWaitFor([&]{return !controller.geometryEditState()["calculating"].toBool();},5000)&&controller.geometryAdvanceStage()&&controller.geometrySelectTerritoryMethod("components")&&QTest::qWaitFor([&]{return !controller.geometryEditState()["calculating"].toBool();},5000);
}
static bool startComponents(EditorController& controller,const QStringList& donors={"donor0"}) {
 controller.selectCountry("target");if(!controller.beginAnnexGeometry())return false;
 for(const auto& donor:donors)if(!controller.geometryToggleProvider({{"domain","territorial"},{"id",donor}}))return false;
 return advanceComponents(controller);
}
private slots:
 void actualSerbiaPostSourceCancellationSuppressesStaleWork_data() {
  QTest::addColumn<QString>("change");QTest::addColumn<int>("postSourceDelayMs");QTest::newRow("cancel-session")<<QString("cancel")<<100;QTest::newRow("replace-donor-epoch")<<QString("donor")<<100;QTest::newRow("cancel-session-long-computation-window")<<QString("cancel")<<1000;QTest::newRow("replace-donor-epoch-long-computation-window")<<QString("donor")<<1000;
 }
 void actualSerbiaPostSourceCancellationSuppressesStaleWork() {
  QFETCH(QString,change);QFETCH(int,postSourceDelayMs);const auto full=qEnvironmentVariable("PANDOEDITOR_HYDRO_FULL_MANIFEST");QVERIFY2(!full.isEmpty(),"required full fixture env missing");
  const auto countriesPath=QFileInfo(QString::fromUtf8(__FILE__)).dir().filePath("fixtures/web-m972-river/countries.json");const auto countryBytes=river_controller_fixture::read(countriesPath);QCOMPARE(QCryptographicHash::hash(countryBytes,QCryptographicHash::Sha256).toHex(),QByteArray("0e1004df101547b5a671934495dfc8b1ab4d06c38b783ae3ca38e82a9cc79e88"));
  Geometry serbia;for(const auto& value:QJsonDocument::fromJson(countryBytes).object()["features"].toArray()){const auto row=value.toObject();if(row["id"]!="SRB")continue;const auto shape=row["geometry"].toObject();serbia.type=shape["type"].toString().toStdString();auto polygons=shape["coordinates"].toArray();if(serbia.type=="Polygon")polygons=QJsonArray{polygons};for(const auto& polygon:polygons){Polygon rings;for(const auto& ring:polygon.toArray()){Ring points;for(const auto& coordinate:ring.toArray()){const auto point=coordinate.toArray();points.push_back({point[0].toDouble(),point[1].toDouble()});}rings.push_back(std::move(points));}serbia.polygons.push_back(std::move(rings));}}
  QVERIFY(!serbia.polygons.empty());QTemporaryDir dir;const auto url=writeProject(dir.filePath("real-serbia-cancel.json"),2,80,30,full);
  changeProject(url,[&](ProjectDocument& d){d.geometries.insert({"donor0",2},serbia);staticGeometryBinding(d,"donor0").geometryRef={"donor0",2};auto replacement=*d.geometries.get({"donor1",1});for(auto& polygon:replacement.polygons)for(auto& ring:polygon)for(auto& point:ring){point.x+=90;point.y-=90;}d.geometries.insert({"donor1",2},replacement);staticGeometryBinding(d,"donor1").geometryRef={"donor1",2};d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);QVERIFY(!provider->queryLogicalRivers(riverPartitionQueryBounds(serbia)).empty());
  QTRY_COMPARE_WITH_TIMEOUT(QThreadPool::globalInstance()->activeThreadCount(),0,15000);const auto baseline=provider->resourceCacheSnapshot();QCOMPARE(baseline.pendingCount,std::size_t(0));const auto identity=*provider->sourceIdentity();const auto bytes=c.documentBytes();const auto revision=c.revision(),presentation=c.presentationRevision();QVERIFY(!c.canUndo());
  QSignalSpy jobChanged(&c,&EditorController::jobChanged);QVERIFY(c.geometryToggleRiverBoundaries(true));QElapsedTimer elapsed;elapsed.start();bool copied=false,postSource=false;qint64 sourceCompletedMs=-1;
  while(elapsed.elapsed()<15000){const auto resources=provider->resourceCacheSnapshot();const auto state=c.geometryEditState();if(state["riverSourceDispatches"].toInt()==1&&resources.pendingCount>baseline.pendingCount)copied=true;if(copied&&resources.pendingCount==baseline.pendingCount&&resources.failureCount==baseline.failureCount&&provider->cachedPackCount()>0&&state["riverStatus"].toString()=="pending"&&QThreadPool::globalInstance()->activeThreadCount()>0){postSource=true;sourceCompletedMs=elapsed.elapsed();break;}if(state["riverStatus"].toString()=="ready"||state["riverStatus"].toString()=="sourceError"||state["riverStatus"].toString()=="error")break;QCoreApplication::processEvents(QEventLoop::AllEvents,1);std::this_thread::yield();}
  QVERIFY2(copied&&postSource,"required real Serbia source-completion/still-running computation window was not observed");
  // Like D2's real Serbia cancellation probe, require a still-running window.
  // The longer rows use 1 s versus D2's observed roughly 3.8 s kernel compute.
  // Source-copy completion narrows this to the production kernel/presentation
  // pipeline. This observes no exact synchronous JavaScript call-entry hook.
  QTest::qWait(postSourceDelayMs);QCOMPARE(c.geometryEditState()["riverStatus"].toString(),QString("pending"));QVERIFY(c.geometryEditState()["calculating"].toBool());QVERIFY(QThreadPool::globalInstance()->activeThreadCount()>0);QCOMPARE(provider->resourceCacheSnapshot().pendingCount,baseline.pendingCount);QCOMPARE(provider->resourceCacheSnapshot().failureCount,baseline.failureCount);QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);QCOMPARE(c.presentationRevision(),presentation);QVERIFY(!c.confirmGeometryEdit());const auto stoppedAtMs=elapsed.elapsed();
  if(change=="cancel"){c.cancelGeometryEdit();QVERIFY(!c.geometryEditState()["active"].toBool());QVERIFY(c.riverSelectionObservation().isEmpty());QVERIFY(!c.confirmGeometryEdit());}
  else {QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor1"}}));QCOMPARE(c.geometryEditState()["stage"].toString(),QString("setup"));QCOMPARE(c.geometryEditState()["riverStatus"].toString(),QString("idle"));QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QVERIFY(!c.confirmGeometryEdit());}
  // Cancellation detaches ownership immediately; synchronous JS may continue
  // on its worker until the next cooperative check. Never call that an interrupt.
  QVERIFY(QThreadPool::globalInstance()->activeThreadCount()>0);if(postSourceDelayMs>=1000){QTest::qWait(100);QVERIFY2(QThreadPool::globalInstance()->activeThreadCount()>0,"long computation did not remain active after cooperative cancellation");}QCoreApplication::processEvents(QEventLoop::AllEvents,1);jobChanged.clear();
  QTRY_VERIFY_WITH_TIMEOUT(jobChanged.count()>0,15000);QTRY_COMPARE_WITH_TIMEOUT(QThreadPool::globalInstance()->activeThreadCount(),0,15000);QCoreApplication::processEvents(QEventLoop::AllEvents,1);const auto oldCompletionMs=elapsed.elapsed();
  QCOMPARE(provider->resourceCacheSnapshot().pendingCount,baseline.pendingCount);QCOMPARE(provider->resourceCacheSnapshot().failureCount,baseline.failureCount);QCOMPARE(provider->resourceCacheSnapshot().protectionCounts[std::size_t(ResourceProtection::InFlight)],baseline.protectionCounts[std::size_t(ResourceProtection::InFlight)]);QVERIFY(*provider->sourceIdentity()==identity);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);QCOMPARE(c.presentationRevision(),presentation);QVERIFY(!c.canUndo());
  if(change=="cancel"){QVERIFY(!c.geometryEditState()["active"].toBool());QVERIFY(c.riverSelectionObservation().isEmpty());QVERIFY(startComponents(c,{"donor1"}));}
  else {QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);const auto features=c.riverSelectionObservation()["componentFeatures"].toList();QCOMPARE(features.size(),1);QCOMPARE(features[0].toMap()["id"].toString(),QString("donor1"));QVERIFY(advanceComponents(c));}
  QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),change=="cancel"?1:2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["loadedRivers"].toInt(),0);for(const auto& component:c.riverSelectionObservation()["components"].toList())QCOMPARE(component.toMap()["countryId"].toString(),QString("donor1"));QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);QCOMPARE(c.presentationRevision(),presentation);QVERIFY(!c.canUndo());QVERIFY(!c.confirmGeometryEdit());
  qInfo().noquote()<<QString("REAL_SERBIA_POST_SOURCE_CANCEL change=%1 postSourceDelayMs=%2 sourceCompletedMs=%3 stopRequestedMs=%4 oldWorkerCompletedMs=%5 exactJsEntryObserved=false hardInterruptClaimed=false").arg(change).arg(postSourceDelayMs).arg(sourceCompletedMs).arg(stoppedAtMs).arg(oldCompletionMs);
 }
 void repairRetryFirstProviderOpenCannotWriteIntoReplacementSession() {
  FixtureCopy fixture;const auto savedManifest=fixture.manifestPath+".saved";QVERIFY(QFile::rename(fixture.manifestPath,savedManifest));QTemporaryDir dir;const auto url=writeProject(dir.filePath("first-open-replaced.json"),1,40,0,fixture.manifestPath);
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("sourceError"),5000);QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),0);
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);QVERIFY(!provider->isOpen());QVERIFY(QFile::rename(savedManifest,fixture.manifestPath));bool firstOpen=false,reopened=false,replaced=false;int dispatchesAtOpen=-1;
  const auto connection=connect(provider,&HydroRuntimeProvider::frameChanged,&c,[&]{if(firstOpen||!provider->isOpen())return;firstOpen=true;dispatchesAtOpen=c.geometryEditState()["riverSourceDispatches"].toInt();c.cancelGeometryEdit();reopened=c.openFile(url);c.selectCountry("target");replaced=c.beginAnnexGeometry()&&c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}});},Qt::DirectConnection);
  QVERIFY(c.geometryRetryRiverPartitions());QTRY_VERIFY_WITH_TIMEOUT(firstOpen,5000);disconnect(connection);QVERIFY(reopened);QVERIFY(replaced);QCOMPARE(dispatchesAtOpen,0);QTRY_VERIFY_WITH_TIMEOUT(!c.geometryEditState()["calculating"].toBool(),5000);
  QVERIFY2(c.geometryEditState()["riverSourceDispatches"].toInt()==0,qPrintable(QString("old first-open continuation dispatched into replacement session: %1").arg(c.geometryEditState()["riverSourceDispatches"].toInt())));QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
  QVERIFY(advanceComponents(c));QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.documentBytes(),bytes);
 }
 void unrelatedProviderOpenCannotBecomeWaitingDefaultBootstrapIdentity() {
  const auto full=qEnvironmentVariable("PANDOEDITOR_HYDRO_FULL_MANIFEST");QVERIFY(!full.isEmpty());FixtureCopy unrelated;QTemporaryDir dir;const auto external=dir.filePath("external"),sourceRoot=QFileInfo(full).dir().absolutePath()+"/..";
  QDirIterator files(sourceRoot,QDir::Files,QDirIterator::Subdirectories);while(files.hasNext()){const auto source=files.next(),destination=external+"/world/c0bd31d1/hydro/"+QDir(sourceRoot).relativeFilePath(source);QDir().mkpath(QFileInfo(destination).path());QVERIFY(QFile::copy(source,destination));}
  river_controller_fixture::ScopedEnvironment externalEnv("PANDOEDITOR_WORLD_DATA_ROOT",external),dataEnv("XDG_DATA_HOME",dir.filePath("data"));
  const auto blocker=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/physical-data/world/c0bd31d1/hydro/v0.13.0";QDir().mkpath(QFileInfo(blocker).path());river_controller_fixture::write(blocker,"not a directory");
  const auto url=writeProject(dir.filePath("unrelated-first-open.json"));changeProject(url,[](ProjectDocument& d){d.physicalData.source.clear();d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());auto* store=c.findChild<PhysicalDataStore*>();QVERIFY(provider);QVERIFY(store);QVERIFY(!provider->isOpen());bool observedReady=false,reused=false,waiting=false,opened=false;QString error;
  const auto connection=connect(store,&PhysicalDataStore::assetReady,&c,[&](const QString& path,const QString&,bool present){if(observedReady||path!="hydro/v0.13.0/index.bin.gz")return;observedReady=true;reused=present;waiting=c.geometryEditState()["riverStatus"].toString()=="pending"&&c.geometryEditState()["calculating"].toBool()&&c.geometryEditState()["riverSourceDispatches"].toInt()==0&&!provider->sourceIdentity();opened=provider->open(unrelated.manifestPath,c.projectInstanceId(),false,error);},Qt::DirectConnection);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_VERIFY_WITH_TIMEOUT(observedReady,5000);disconnect(connection);QVERIFY(reused);QVERIFY(waiting);QVERIFY2(opened,qPrintable(error));QTRY_VERIFY_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString()!="pending",15000);
  const auto state=c.geometryEditState();QVERIFY2(state["riverSourceDispatches"].toInt()==0,qPrintable(QString("unrelated provider accepted as bootstrap: status=%1 source=%2 kernel=%3 cache=%4").arg(state["riverStatus"].toString()).arg(state["riverSourceDispatches"].toInt()).arg(state["riverKernelDispatches"].toInt()).arg(state["riverCacheEntries"].toInt())));QCOMPARE(state["riverStatus"].toString(),QString("error"));QCOMPARE(state["riverKernelDispatches"].toInt(),0);QCOMPARE(state["riverCacheEntries"].toInt(),0);QVERIFY(!state["calculating"].toBool());QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
  c.cancelGeometryEdit();provider->close(c.projectInstanceId());QVERIFY(QFile::remove(blocker));QVERIFY(startComponents(c));QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(provider->sourceIdentity()->dataset,QJsonDocument::fromJson(river_controller_fixture::read(full)).object()["dataset"].toString());QCOMPARE(c.documentBytes(),bytes);
 }
 void missingCustomManifestRepairFreezesFirstLoadedIdentity() {
  FixtureCopy fixture;fixture.manifest["dataset"]="foreign-first-open";fixture.save();
  const auto savedManifest=fixture.manifestPath+".saved";QVERIFY(QFile::rename(fixture.manifestPath,savedManifest));
  QTemporaryDir dir;const auto url=writeProject(dir.filePath("missing-manifest.json"),1,40,0,fixture.manifestPath);
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));
  const auto bytes=c.documentBytes();const auto revision=c.revision(),presentation=c.presentationRevision();
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("sourceError"),5000);
  QVERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);
  QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);QCOMPARE(c.presentationRevision(),presentation);QVERIFY(!c.canUndo());
  QVERIFY(QFile::rename(savedManifest,fixture.manifestPath));QVERIFY(c.geometryRetryRiverPartitions());
  QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  const auto identity=c.riverSelectionObservation()["sourceDiagnostics"].toMap();
  QCOMPARE(identity["indexSha256"].toString(),fixture.manifest["index"].toObject()["sha256"].toString());QCOMPARE(identity["version"].toString(),QString("0.13.1"));QVERIFY(identity["generation"].toULongLong()>0);QCOMPARE(identity["loadedRivers"].toInt(),1);
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);QCOMPARE(provider->sourceIdentity()->dataset,QString("foreign-first-open"));
  QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());
  QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);QCOMPARE(c.presentationRevision(),presentation);QVERIFY(!c.canUndo());
 }
 void missingCustomDetailNeverInvokesKernelAndRepairRetries() {
  FixtureCopy fixture;const auto detail=fixture.path("v0.13.0/metadata-detail.json.gz");const auto saved=river_controller_fixture::read(detail);QVERIFY(QFile::remove(detail));
  QTemporaryDir dir;EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(writeProject(dir.filePath("detail-error.json"),1,40,0,fixture.manifestPath)));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("sourceError"),15000);QVERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QVERIFY(!c.geometryEditState()["riverError"].toString().isEmpty());QVERIFY(c.geometryEditState()["components"].toList().isEmpty());QCOMPARE(c.documentBytes(),bytes);
  river_controller_fixture::write(detail,saved);QVERIFY(c.geometryRetryRiverPartitions());QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QVERIFY(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["failedLogicalIds"].toList().isEmpty());QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
 }
 void partialLogicalFailureKeepsActualIdsAndRepairBypassesCache() {
  FixtureCopy fixture;fixture.splitLastFragment();const auto lastShard=fixture.path("v0.13.0/shards/s1.bin");const auto saved=river_controller_fixture::read(lastShard);QVERIFY(QFile::remove(lastShard));
  QTemporaryDir dir;const auto url=writeProject(dir.filePath("partial.json"),2,0,0,fixture.manifestPath);
  changeProject(url,[](ProjectDocument& d){auto geometry=*d.geometries.get({"donor1",1});for(auto& polygon:geometry.polygons)for(auto& ring:polygon)for(auto& point:ring)point.x+=39.8;d.geometries.insert({"donor1",2},geometry);staticGeometryBinding(d,"donor1").geometryRef={"donor1",2};});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c,{"donor0","donor1"}));const auto bytes=c.documentBytes();
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);const auto requirements=provider->riverPartitionAssetRequirements({{40,0,40.1,.1,false}});QCOMPARE(requirements.size(),std::size_t(3));QCOMPARE(requirements.back().asset.path,lastShard);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  auto diagnostics=c.riverSelectionObservation()["sourceDiagnostics"].toMap();QCOMPARE(diagnostics["loadedRivers"].toInt(),1);QCOMPARE(diagnostics["failedLogicalIds"].toList(),QVariantList{QVariant::fromValue(qulonglong(5))});QVERIFY(!c.geometryEditState()["riverWarning"].toString().isEmpty());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.documentBytes(),bytes);
  const auto generation=diagnostics["generation"];river_controller_fixture::write(lastShard,saved);
  QVERIFY(c.geometryToggleRiverBoundaries(false));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  QVERIFY(c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["failedLogicalIds"].toList(),diagnostics["failedLogicalIds"].toList());QVERIFY(!c.geometryEditState()["riverWarning"].toString().isEmpty());
  QVERIFY(c.geometryRetryRiverPartitions());QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());diagnostics=c.riverSelectionObservation()["sourceDiagnostics"].toMap();
  QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(diagnostics["loadedRivers"].toInt(),2);QVERIFY(diagnostics["failedLogicalIds"].toList().isEmpty());QVERIFY(c.geometryEditState()["riverWarning"].toString().isEmpty());QCOMPARE(diagnostics["generation"],generation);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
 }
 void synchronousAssetReadyCanCancelPreparationWithoutInstalling() {
  const auto full=qEnvironmentVariable("PANDOEDITOR_HYDRO_FULL_MANIFEST");QVERIFY(!full.isEmpty());QTemporaryDir dir;
  const auto external=dir.filePath("external"),sourceRoot=QFileInfo(full).dir().absolutePath()+"/..";
  QDirIterator files(sourceRoot,QDir::Files,QDirIterator::Subdirectories);while(files.hasNext()){const auto source=files.next(),destination=external+"/world/c0bd31d1/hydro/"+QDir(sourceRoot).relativeFilePath(source);QDir().mkpath(QFileInfo(destination).path());QVERIFY(QFile::copy(source,destination));}
  river_controller_fixture::ScopedEnvironment externalEnv("PANDOEDITOR_WORLD_DATA_ROOT",external),dataEnv("XDG_DATA_HOME",dir.filePath("data"));
  const auto blocker=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/physical-data/world/c0bd31d1/hydro/v0.13.0";QDir().mkpath(QFileInfo(blocker).path());river_controller_fixture::write(blocker,"not a directory");
  const auto url=writeProject(dir.filePath("sync-cancel.json"));changeProject(url,[](ProjectDocument& d){d.physicalData.source.clear();d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();
  auto* store=c.findChild<PhysicalDataStore*>();QVERIFY(store);bool cancelled=false,reused=false;int sourceDispatches=-1,kernelDispatches=-1;
  const auto connection=connect(store,&PhysicalDataStore::assetReady,&c,[&](const QString& path,const QString&,bool present){if(cancelled||path!="hydro/v0.13.0/index.bin.gz")return;cancelled=true;reused=present;sourceDispatches=c.geometryEditState()["riverSourceDispatches"].toInt();kernelDispatches=c.geometryEditState()["riverKernelDispatches"].toInt();c.cancelGeometryEdit();},Qt::DirectConnection);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_VERIFY_WITH_TIMEOUT(cancelled,5000);disconnect(connection);
  QVERIFY(reused);QCOMPARE(sourceDispatches,0);QCOMPARE(kernelDispatches,0);QVERIFY(!c.geometryEditState()["active"].toBool());QVERIFY(c.riverSelectionObservation().isEmpty());QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
  QVERIFY(QFile::remove(blocker));QVERIFY(startComponents(c));QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.documentBytes(),bytes);
 }
 void donorChangeAfterRealDispatchDropsOldResultAndCacheEntry() {
  QTemporaryDir dir;EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(writeProject(dir.filePath("donor-race.json"),2,40,0)));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();
  bool changed=false,removed=false,added=false;const auto connection=connect(&c,&EditorController::geometryEditChanged,&c,[&]{const auto state=c.geometryEditState();if(changed||state["riverSourceDispatches"].toInt()!=1||state["riverStatus"].toString()!="pending")return;changed=true;removed=c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}});added=c.geometryToggleProvider({{"domain","territorial"},{"id","donor1"}});},Qt::DirectConnection);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_VERIFY_WITH_TIMEOUT(changed,5000);disconnect(connection);QVERIFY(removed);QVERIFY(added);QVERIFY(advanceComponents(c));
  QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);
  const auto observation=c.riverSelectionObservation();QCOMPARE(observation["componentFeatures"].toList().size(),1);QCOMPARE(observation["componentFeatures"].toList()[0].toMap()["id"].toString(),QString("donor1"));for(const auto& component:observation["components"].toList())QCOMPARE(component.toMap()["countryId"].toString(),QString("donor1"));QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
 }
 void inFlightSourceChangesDiscardResultsAndReleaseProtection_data() {
  QTest::addColumn<QString>("change");QTest::newRow("toggle-off")<<QString("toggle");QTest::newRow("cancel-edit")<<QString("cancel");QTest::newRow("identical-provider-reopen")<<QString("reopen");
 }
 void inFlightSourceChangesDiscardResultsAndReleaseProtection() {
  QFETCH(QString,change);FixtureCopy fixture;fixture.enlargeValidDetail();QTemporaryDir dir;const auto url=writeProject(dir.filePath("source-copy-cancel.json"),1,40,0,fixture.manifestPath);
  changeProject(url,[](ProjectDocument& d){d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();const auto originalComponents=c.riverSelectionObservation()["components"].toList();auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);const auto identity=*provider->sourceIdentity();
  QTRY_COMPARE_WITH_TIMEOUT(provider->resourceCacheSnapshot().pendingCount,std::size_t(0),5000);const auto baseline=provider->resourceCacheSnapshot();const auto inFlight=std::size_t(ResourceProtection::InFlight);
  // beginCopy is pending during detail decoding even before any pack is resident.
  // InFlight counts apply to resident packs; both diagnostics must return to baseline.
  QVERIFY(c.geometryToggleRiverBoundaries(true));QElapsedTimer wait;wait.start();bool observedCopy=false;
  while(wait.elapsed()<5000){const auto resources=provider->resourceCacheSnapshot();if(c.geometryEditState()["riverSourceDispatches"].toInt()==1&&resources.pendingCount>baseline.pendingCount){observedCopy=true;break;}if(c.geometryEditState()["riverStatus"].toString()=="ready")break;QCoreApplication::processEvents(QEventLoop::AllEvents,1);std::this_thread::yield();}
  QVERIFY2(observedCopy,"did not observe the real source's active copy token");QCOMPARE(c.geometryEditState()["riverStatus"].toString(),QString("pending"));QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);
  if(change=="toggle")QVERIFY(c.geometryToggleRiverBoundaries(false));
  else if(change=="cancel")c.cancelGeometryEdit();
  else {QString error;QVERIFY2(provider->open(fixture.manifestPath,c.projectInstanceId(),false,error),qPrintable(error));QCOMPARE(provider->sourceIdentity()->dataset,identity.dataset);QCOMPARE(provider->sourceIdentity()->version,identity.version);QCOMPARE(provider->sourceIdentity()->indexSha256,identity.indexSha256);QVERIFY(provider->sourceIdentity()->generation>identity.generation);QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("error"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);}
  QTRY_COMPARE_WITH_TIMEOUT(provider->resourceCacheSnapshot().pendingCount,baseline.pendingCount,5000);QTRY_COMPARE_WITH_TIMEOUT(provider->resourceCacheSnapshot().protectionCounts[inFlight],baseline.protectionCounts[inFlight],5000);
  if(change=="toggle"){QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverStatus"].toString(),QString("idle"));QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.riverSelectionObservation()["components"].toList(),originalComponents);}
  else if(change=="cancel"){QVERIFY(!c.geometryEditState()["active"].toBool());QVERIFY(c.riverSelectionObservation().isEmpty());QVERIFY(startComponents(c));}
  QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);
  if(change=="reopen")QVERIFY(c.geometryRetryRiverPartitions());else QVERIFY(c.geometryToggleRiverBoundaries(true));
  QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),change=="cancel"?1:2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(provider->resourceCacheSnapshot().pendingCount,baseline.pendingCount);QCOMPARE(provider->resourceCacheSnapshot().protectionCounts[inFlight],baseline.protectionCounts[inFlight]);QCOMPARE(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["generation"].toULongLong(),provider->sourceIdentity()->generation);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
 }
 void identicalProviderReopenClearsSuccessfulCacheImmediately() {
  FixtureCopy fixture;QTemporaryDir dir;EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(writeProject(dir.filePath("cached-generation.json"),1,40,0,fixture.manifestPath)));QVERIFY(startComponents(c));const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);const auto identity=*provider->sourceIdentity();QString error;QVERIFY2(provider->open(fixture.manifestPath,c.projectInstanceId(),false,error),qPrintable(error));QCOMPARE(provider->sourceIdentity()->dataset,identity.dataset);QCOMPARE(provider->sourceIdentity()->version,identity.version);QCOMPARE(provider->sourceIdentity()->indexSha256,identity.indexSha256);QVERIFY(provider->sourceIdentity()->generation>identity.generation);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);
  QVERIFY(c.geometryRetryRiverPartitions());QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["generation"].toULongLong(),provider->sourceIdentity()->generation);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());
 }
 void supportedReplacementAfterDispatchDiscardsCancelledCompletion_data() {
  QTest::addColumn<QString>("replacement");QTest::newRow("project-reopen")<<QString("project");QTest::newRow("source-replacement")<<QString("source");
 }
 void supportedReplacementAfterDispatchDiscardsCancelledCompletion() {
  QFETCH(QString,replacement);FixtureCopy fixture;FixtureCopy replacementFixture;replacementFixture.manifest["dataset"]="replacement-fixture";replacementFixture.save();QTemporaryDir dir;
  const auto url=writeProject(dir.filePath("replacement-race.json"),1,40,0,fixture.manifestPath);EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto original=c.documentBytes();
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);const auto generation=provider->sourceIdentity()->generation;
  bool dispatched=false,openRejected=false,sourceRejected=false,unchanged=false,replaced=false;
  const auto connection=connect(&c,&EditorController::geometryEditChanged,&c,[&]{const auto state=c.geometryEditState();if(dispatched||state["riverSourceDispatches"].toInt()!=1||state["riverStatus"].toString()!="pending")return;dispatched=true;openRejected=!c.openFile(url);sourceRejected=!c.configureHydroData(QUrl::fromLocalFile(replacementFixture.manifestPath));unchanged=c.documentBytes()==original;c.cancelGeometryEdit();replaced=replacement=="project"?c.openFile(url):c.configureHydroData(QUrl::fromLocalFile(replacementFixture.manifestPath));},Qt::DirectConnection);
  QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_VERIFY_WITH_TIMEOUT(dispatched,5000);disconnect(connection);QVERIFY(openRejected);QVERIFY(sourceRejected);QVERIFY(unchanged);QVERIFY(replaced);QVERIFY(!c.geometryEditState()["active"].toBool());QVERIFY(c.riverSelectionObservation().isEmpty());QVERIFY(provider->sourceIdentity()->generation>generation);
  if(replacement=="source")QCOMPARE(provider->sourceIdentity()->dataset,QString("replacement-fixture"));else QCOMPARE(c.documentBytes(),original);
  const auto bytes=c.documentBytes();const auto revision=c.revision();QVERIFY(startComponents(c));QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),0);QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["generation"].toULongLong(),provider->sourceIdentity()->generation);QCOMPARE(c.documentBytes(),bytes);QCOMPARE(c.revision(),revision);
 }
 void hiddenOffscreenEditedGeometryChangesCacheAndHydroRevision() {
  QTemporaryDir dir;const auto url=writeProject(dir.filePath("edited-signature.json"),1,40,0);
  changeProject(url,[](ProjectDocument& d){Geometry line;line.type="LineString";line.lines={{{80,30},{81,31}}};const GeometryRef ref{"hidden-edit",1};d.geometries.insert(ref,line);HydroFeature edit;edit.id="hidden-edit";edit.name="Hidden offscreen river";edit.kind="river";edit.geometry=ref;edit.source.kind="user";edit.sourceFeatureId="fixture:5";d.hydro.push_back(edit);d.physicalData.hiddenHydroIds.push_back(edit.id);d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;});
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));QVERIFY(startComponents(c));const auto original=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  const auto first=c.riverSelectionObservation();const auto signature=first["editedRiverSignature"];QVERIFY(!signature.toString().isEmpty());QVERIFY(signature.toString().contains("hidden-edit"));QCOMPARE(first["sourceDiagnostics"].toMap()["loadedRivers"].toInt(),1);QCOMPARE(c.documentBytes(),original);QCOMPARE(c.revision(),qulonglong(0));QVERIFY(!c.canUndo());c.cancelGeometryEdit();
  auto* provider=qobject_cast<HydroRuntimeProvider*>(c.hydroSource());QVERIFY(provider);const auto generation=provider->sourceIdentity()->generation;
  QVERIFY(c.selectObject({{"domain","hydro"},{"id","hidden-edit"}}));QVERIFY(c.beginContentEdit("hydro"));QVERIFY(c.beginContentGeometry());QVERIFY(c.geometrySetMoveMode(true));QVERIFY(c.geometryBeginObjectDrag());QVERIFY(c.geometryTranslateObject(1,0));c.geometryEndObjectDrag();QVERIFY(c.requestGeometryPreview());QVERIFY(c.confirmGeometryEdit());QCOMPARE(c.revision(),qulonglong(1));QVERIFY(c.canUndo());QCOMPARE(provider->sourceIdentity()->generation,generation);
  const auto editedBytes=c.documentBytes();QVERIFY(editedBytes!=original);QVERIFY(startComponents(c));QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  const auto second=c.riverSelectionObservation();QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),2);QVERIFY(second["editedRiverSignature"]!=signature);QVERIFY(second["hydroRevision"]!=first["hydroRevision"]);QCOMPARE(second["sourceDiagnostics"].toMap()["generation"],first["sourceDiagnostics"].toMap()["generation"]);QCOMPARE(second["sourceDiagnostics"].toMap()["loadedRivers"].toInt(),1);QCOMPARE(c.documentBytes(),editedBytes);QCOMPARE(c.revision(),qulonglong(1));
 }
 void defaultExternalAssetsArePromotedToCoherentTree() {
  const auto full=qEnvironmentVariable("PANDOEDITOR_HYDRO_FULL_MANIFEST");QVERIFY2(!full.isEmpty(),"required full fixture env missing");
  QTemporaryDir dir;const auto external=dir.filePath("external");const auto sourceRoot=QFileInfo(full).dir().absolutePath()+"/..";
  QDirIterator it(sourceRoot,QDir::Files,QDirIterator::Subdirectories);while(it.hasNext()){const auto source=it.next();const auto relative=QDir(sourceRoot).relativeFilePath(source);const auto target=external+"/world/c0bd31d1/hydro/"+relative;QDir().mkpath(QFileInfo(target).path());QVERIFY(QFile::copy(source,target));}
  const auto oldExternal=qgetenv("PANDOEDITOR_WORLD_DATA_ROOT"),oldData=qgetenv("XDG_DATA_HOME");qputenv("PANDOEDITOR_WORLD_DATA_ROOT",external.toUtf8());qputenv("XDG_DATA_HOME",dir.filePath("data").toUtf8());
  auto url=writeProject(dir.filePath("default.json"),1,20.4,44.8);QFile input(url.toLocalFile());QVERIFY(input.open(QIODevice::ReadOnly));auto d=projectcodec::decode(input.readAll());input.close();d.physicalData.source.clear();d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;Project p;p.replace(d);QVERIFY(input.open(QIODevice::WriteOnly));input.write(projectcodec::encode(p));input.close();
  {EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),30000);QCOMPARE(c.documentBytes(),bytes);
   const auto cache=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/physical-data/world/c0bd31d1/hydro/";
   for(const auto name:{"v0.13.1/manifest.json","v0.13.0/index.bin.gz","v0.13.1/metadata-core.json.gz","v0.13.0/metadata-detail.json.gz"})QVERIFY2(QFileInfo::exists(cache+name),name);
   QVERIFY(c.riverSelectionObservation()["sourceDiagnostics"].toMap()["loadedRivers"].toInt()>0);
  }
  qputenv("PANDOEDITOR_WORLD_DATA_ROOT",oldExternal);qputenv("XDG_DATA_HOME",oldData);
 }
 void failedExternalPromotionSettlesAsSourceError() {
  const auto full=qEnvironmentVariable("PANDOEDITOR_HYDRO_FULL_MANIFEST");QVERIFY(!full.isEmpty());QTemporaryDir dir;const auto external=dir.filePath("external"),sourceRoot=QFileInfo(full).dir().absolutePath()+"/..";
  QDirIterator it(sourceRoot,QDir::Files,QDirIterator::Subdirectories);while(it.hasNext()){const auto source=it.next(),target=external+"/world/c0bd31d1/hydro/"+QDir(sourceRoot).relativeFilePath(source);QDir().mkpath(QFileInfo(target).path());QVERIFY(QFile::copy(source,target));}
  const auto oldExternal=qgetenv("PANDOEDITOR_WORLD_DATA_ROOT"),oldData=qgetenv("XDG_DATA_HOME");qputenv("PANDOEDITOR_WORLD_DATA_ROOT",external.toUtf8());qputenv("XDG_DATA_HOME",dir.filePath("data").toUtf8());
  const auto blocker=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/physical-data/world/c0bd31d1/hydro/v0.13.0";QDir().mkpath(QFileInfo(blocker).path());QFile block(blocker);QVERIFY(block.open(QIODevice::WriteOnly));block.write("not a directory");block.close();
  auto url=writeProject(dir.filePath("blocked.json"));QFile f(url.toLocalFile());QVERIFY(f.open(QIODevice::ReadOnly));auto d=projectcodec::decode(f.readAll());f.close();d.physicalData.source.clear();d.presentation.webPresentation.visibility["rivers"]=false;d.presentation.webPresentation.visibility["lakes"]=false;Project p;p.replace(d);QVERIFY(f.open(QIODevice::WriteOnly));f.write(projectcodec::encode(p));f.close();
  {EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("sourceError"),5000);QVERIFY(!c.geometryEditState()["calculating"].toBool());QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),0);QCOMPARE(c.documentBytes(),bytes);QVERIFY(QFile::remove(blocker));QVERIFY(c.geometryRetryRiverPartitions());QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QCOMPARE(c.documentBytes(),bytes);}
  qputenv("PANDOEDITOR_WORLD_DATA_ROOT",oldExternal);qputenv("XDG_DATA_HOME",oldData);
 }
 void identicalPreparationUsesCacheAndRetryBypasses() {
  QTemporaryDir dir;auto url=writeProject(dir.filePath("cache.json"));EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(url));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["components"].toList().size(),1);
  QVERIFY(c.geometryToggleRiverBoundaries(false));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QVERIFY(c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),1);QCOMPARE(c.geometryEditState()["riverKernelDispatches"].toInt(),1);
  QVERIFY(c.geometryRetryRiverPartitions());QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),2);QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),1);QCOMPARE(c.documentBytes(),bytes);
 }
 void fifoCacheHasEightEntriesAndHitsDoNotPromote() {
  QTemporaryDir dir;EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(writeProject(dir.filePath("fifo.json"),10)));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));
  auto partition=[&](){QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryToggleRiverBoundaries(true));QTRY_COMPARE_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString(),QString("ready"),15000);};
  partition();for(int i=1;i<=7;++i){if(i>1)QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id",QString("donor%1").arg(i-1)}}));QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id",QString("donor%1").arg(i)}}));partition();}
  QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),8);QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor7"}}));partition();QVERIFY(c.geometryEditState()["riverCacheHit"].toBool());
  QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor8"}}));partition();QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverCacheEntries"].toInt(),8);
  QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor8"}}));partition();QVERIFY(!c.geometryEditState()["riverCacheHit"].toBool());QCOMPARE(c.geometryEditState()["riverSourceDispatches"].toInt(),10);
 }
 void cancelBeforeQueuedPreparationDoesNotInstall() {
  QTemporaryDir dir;EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(writeProject(dir.filePath("cancel.json"))));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor0"}}));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());const auto bytes=c.documentBytes();QVERIFY(c.geometryToggleRiverBoundaries(true));c.cancelGeometryEdit();QTest::qWait(200);QVERIFY(!c.geometryEditState()["active"].toBool());QCOMPARE(c.documentBytes(),bytes);
 }

 void realSourceToggleIsAvailableOnlyInComponents() {
  QTemporaryDir dir; ProjectDocument d({{"target","Target",{{{{50,0},{51,0},{51,1},{50,1},{50,0}}}},0}, {"donor","Donor",{{{{39.9,-.1},{40.2,-.1},{40.2,.2},{39.9,.2},{39.9,-.1}}}},0}},{{"countries","Countries"}});
  d.documentId="river-controller"; d.physicalData.source=std::string(WEB_HYDRO_FIXTURE)+"/v0.13.1/manifest.json";
  Project p;p.replace(d);QFile f(dir.filePath("input.json"));QVERIFY(f.open(QIODevice::WriteOnly));f.write(projectcodec::encode(p));f.close();
  EditorController c({false,dir.filePath("private.json")});QVERIFY(c.openFile(QUrl::fromLocalFile(f.fileName())));c.selectCountry("target");QVERIFY(c.beginAnnexGeometry());QVERIFY(c.geometryToggleProvider({{"domain","territorial"},{"id","donor"}}));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());QVERIFY(c.geometryAdvanceStage());QVERIFY(c.geometrySelectTerritoryMethod("components"));QTRY_VERIFY(!c.geometryEditState()["calculating"].toBool());
  const auto before=c.documentBytes();QVERIFY(c.geometryEditState()["canToggleRiverBoundaries"].toBool());
  bool accepted=false;QVERIFY(QMetaObject::invokeMethod(&c,"geometryToggleRiverBoundaries",Q_RETURN_ARG(bool,accepted),Q_ARG(bool,true)));QVERIFY(accepted);
  QTRY_VERIFY_WITH_TIMEOUT(c.geometryEditState()["riverStatus"].toString()=="ready",15000);QCOMPARE(c.documentBytes(),before);QVERIFY(!c.geometryEditState()["components"].toList().empty());
 }
};
QTEST_MAIN(RiverSelectionControllerTests)
#include "river_selection_controller_tests.moc"
