#include <pandoeditor/commands.h>
#include <pandoeditor/project.h>
#include <cassert>
using namespace pandoeditor;
static Geometry box(double x,double y,double n){Geometry g;g.type="Polygon";g.polygons.push_back(Polygon{Ring{{x,y},{x+n,y},{x+n,y+n},{x,y+n},{x,y}}});return g;}
static Project project(){ProjectDocument d({{"A","A",box(0,0,10).polygons,0x112233,"",1,"countries"},{"B","B",box(20,0,10).polygons,0x112233,"",1,"countries"}},{{"countries","Countries"}});auto pg=GeometryRef{"p",1},g=GeometryRef{"s",1};d.geometries.insert(pg,box(1,1,6));d.geometries.insert(g,box(2,2,2));d.units.push_back({"P","P","",UnitKind::Subunit,pg});d.units.back().coverageMode="partition";d.units.push_back({"S","S","",UnitKind::Subunit,g});d.units.back().coverageMode="partition";for(auto id:{"P","S"}){d.presentation.membership[territorialRef(id)]="countries";d.presentation.objectStyles[territorialRef(id)]={};}d.relations.push_back({"p-base",territorialRef("P"),territorialRef("A"),territorialRef("A")});d.relations.push_back({"s-base",territorialRef("S"),territorialRef("P"),territorialRef("A")});Project p;p.replace(d);return p;}
int main(){auto p=project();auto plan=CommandProcessor::planTerritorial(p,ChangeParentIntent{territorialRef("S"),territorialRef("A")});assert(plan.ok()&&plan.plan);CommandArguments args;args.action=ApplyTerritorialMutation{*plan.plan,{}};auto request=CommandProcessor::makeRequest(p,"territorial.relation.parent",args);auto prepared=CommandProcessor::prepare(p,request);assert(prepared.ok());assert(CommandProcessor::confirm(p,*prepared.preview).ok());assert(p.undo());
 auto create=CreateTerritorialIntent{UnitKind::Region,"R","R",box(30,0,2)};auto cp=CommandProcessor::planTerritorial(p,create);assert(cp.ok());args.action=ApplyTerritorialMutation{*cp.plan,{}};request=CommandProcessor::makeRequest(p,"territorial.create",args);prepared=CommandProcessor::prepare(p,request);assert(prepared.ok());assert(CommandProcessor::confirm(p,*prepared.preview).ok());assert(p.index().objects.count(territorialRef("R")));
 auto transfer=CommandProcessor::planTerritorial(p,TransferSubunitIntent{territorialRef("S"),territorialRef("B")});assert(transfer.ok()&&transfer.plan);args.action=ApplyTerritorialMutation{*transfer.plan,GeometryPatch{p.revision(),{{territorialRef("S"),box(2,2,2)},{territorialRef("B"),box(20,0,10)}},{}}};request=CommandProcessor::makeRequest(p,"territorial.geometry.commit",args);prepared=CommandProcessor::prepare(p,request);assert(prepared.ok());assert(CommandProcessor::confirm(p,*prepared.preview).ok());const auto* relation=effectiveRelation(p.document(),"S",19450101);assert(relation&&relation->parent==territorialRef("B")&&relation->sovereign==territorialRef("B"));assert(p.undo());
 auto promote=CommandProcessor::planTerritorial(p,ConvertTerritorialTypeIntent{territorialRef("S"),UnitKind::Country,{},{},{}});assert(promote.ok()&&promote.plan);args.action=ApplyTerritorialMutation{*promote.plan,GeometryPatch{p.revision(),{{territorialRef("S"),box(2,2,2)},{territorialRef("A"),box(0,0,10)}},{}}};request=CommandProcessor::makeRequest(p,"territorial.geometry.commit",args);prepared=CommandProcessor::prepare(p,request);assert(prepared.ok());assert(CommandProcessor::confirm(p,*prepared.preview).ok());assert(p.document().units.at(p.index().objects.at(territorialRef("S"))).kind==UnitKind::Country);assert(p.undo());
 auto demote=CommandProcessor::planTerritorial(p,ConvertTerritorialTypeIntent{territorialRef("A"),UnitKind::Subunit,territorialRef("B"),territorialRef("B"),"A-sub"});assert(demote.ok()&&demote.plan);args.action=ApplyTerritorialMutation{*demote.plan,GeometryPatch{p.revision(),{{territorialRef("A"),box(0,0,10)},{territorialRef("B"),box(20,0,10)}},{}}};request=CommandProcessor::makeRequest(p,"territorial.geometry.commit",args);prepared=CommandProcessor::prepare(p,request);assert(prepared.ok());assert(CommandProcessor::confirm(p,*prepared.preview).ok());assert(!p.index().objects.count(territorialRef("A"))&&p.index().objects.count(territorialRef("A-sub")));assert(p.undo());}
