#include "webimport.h"
#include "losslessjson.h"
#include "projectcodec.h"
#include <QtTest>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
using namespace pandoeditor;
namespace {
QByteArray full(int schema=10,const char* format="pandolab-project-state") {
    QFile file(QStringLiteral(WEB_IMPORT_FIXTURES)+"/../timeline-exchange/static.json");if(!file.open(QIODevice::ReadOnly))throw std::runtime_error("v9 fixture unavailable");
    auto root=QJsonDocument::fromJson(file.readAll()).object();root["schemaVersion"]=schema;root["format"]=format;return QJsonDocument(root).toJson(QJsonDocument::Compact);
}
QString errorFor(const std::function<void()>& f){try{f();}catch(const std::exception& e){return e.what();}return {};}
QJsonObject object(){return QJsonDocument::fromJson(full()).object();}
QByteArray bytes(const QJsonObject& root){return QJsonDocument(root).toJson(QJsonDocument::Compact);}
QJsonObject distributionLayer(){return {{"id","00000000-0000-4000-8000-000000000011"},{"schemaVersion",3},{"name","Population"},{"unit","people"},{"valueScale",QJsonObject{{"mode","manual"},{"min",-100},{"max",2000}}},{"color","#507090"},{"locked",false},{"parentId",""},{"groups",QJsonArray{}},{"validFrom",QJsonValue::Null},{"validTo",QJsonValue::Null},{"metadata",QJsonObject{}}};}
QJsonObject distributionEntry(){return {{"id","00000000-0000-4000-8000-000000000012"},{"schemaVersion",3},{"layerId","00000000-0000-4000-8000-000000000011"},{"mode","territorial"},{"territorialUnitId","A"},{"geometry",QJsonValue::Null},{"value",1500},{"certainty","medium"},{"validFrom",QJsonValue::Null},{"validTo",QJsonValue::Null},{"metadata",QJsonObject{}}};}
}
class WebImportTests:public QObject {
 Q_OBJECT
private slots:
 void currentSchema6ValuesAndManualScale(){auto root=object();root["distributionLayers"]=QJsonArray{distributionLayer()};root["distributionEntries"]=QJsonArray{distributionEntry()};auto candidate=webimport::prepare(bytes(root));QCOMPARE(candidate.document.distributionEntries.front().value,1500.);QCOMPARE(candidate.document.distributionLayers.front().valueScale.min,-100.);Project p;p.replace(candidate.document);Project reopened;reopened.replace(projectcodec::decode(projectcodec::encode(p)));QCOMPARE(projectcodec::encode(reopened),projectcodec::encode(p));}
 void formats(){QCOMPARE(webimport::classify(full()),webimport::FileKind::WebFull);QCOMPARE(webimport::classify(full(10,"pandolab-autosave-full")),webimport::FileKind::WebFull);QCOMPARE(webimport::classify(full(10,"pandolab-autosave-delta")),webimport::FileKind::WebDelta);Project p;p.replace(webimport::prepare(full()).document);QCOMPARE(webimport::classify(projectcodec::encode(p)),webimport::FileKind::QtProject);}
 void rejectAmbiguousOrUnsupported(){for(const auto* format:{"pandolab-project","unknown","FeatureCollection"})QVERIFY_EXCEPTION_THROWN(webimport::prepare(full(10,format)),std::invalid_argument);auto root=object();root["schemaVersion"]="10";QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}
 void oldDevelopmentVersionsReject(){for(int version=1;version<10;++version)QVERIFY_EXCEPTION_THROWN(webimport::prepare(full(version)),std::invalid_argument);}
 void originalJsGoldenMigration(){for(const auto* name:{"static","complex"}){QFile file(QStringLiteral(WEB_IMPORT_FIXTURES)+"/../timeline-exchange/"+name+".json");QVERIFY(file.open(QIODevice::ReadOnly));const auto input=file.readAll();Project p;p.replace(webimport::prepare(input).document);const auto exported=QJsonDocument::fromJson(projectcodec::encodeWeb(p.snapshot())).object(),source=QJsonDocument::fromJson(input).object();QCOMPARE(exported["territorialEntities"],source["territorialEntities"]);QCOMPARE(exported["timelineRecords"],source["timelineRecords"]);QCOMPARE(exported["geometries"],source["geometries"]);}}
 void allSupportedSchemasMapAndReopen(){for(const auto* format:{"pandolab-project-state","pandolab-autosave-full"}){Project p;p.replace(webimport::prepare(full(10,format)).document);const auto saved=projectcodec::encode(p);Project reopened;reopened.replace(projectcodec::decode(saved));QCOMPARE(projectcodec::encode(reopened),saved);}}
 void sourceAndExpandedOutputRespectStorageLimit(){QVERIFY(errorFor([]{webimport::prepare(QByteArray(64*1024*1024+1,' '));}).contains("LIMIT_EXCEEDED"));}
 void mapsEffectiveCountryAndRoundtrip(){auto candidate=webimport::prepare(full());QCOMPARE(candidate.document.units.size(),std::size_t(4));QCOMPARE(candidate.document.countryDetails.at(territorialRef("A")).capital,std::string("서울"));Project p;p.replace(candidate.document);const auto before=projectcodec::encode(p);QVERIFY(p.renameCountry("A","Edited"));QVERIFY(p.undo());QCOMPARE(projectcodec::encode(p),before);QVERIFY(p.redo());QCOMPARE(p.document().countryDetails.at(territorialRef("A")).capital,std::string("서울"));}
 void rejectsBrokenReferencesAndCoordinates(){auto root=object();root["geometries"]=QJsonArray{};QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);root=object();auto records=root["timelineRecords"].toObject();auto parents=records["parentRelations"].toArray();auto parent=parents[0].toObject();parent["parentId"]="missing";parents[0]=parent;records["parentRelations"]=parents;root["timelineRecords"]=records;QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}
 void losslessUnknownAndGuard(){auto root=object();root["future"]=QJsonObject{{"number",42}};QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);auto wire=full();wire.replace("\"originalName\":",R"("exact":9007199254740993123456789,"originalName":)");Project p;p.replace(webimport::prepare(wire).document);const auto native=projectcodec::encode(p.snapshot());QVERIFY(native.contains("9007199254740993123456789"));Project reopened;reopened.replace(projectcodec::decode(native));QCOMPARE(projectcodec::encode(reopened.snapshot()),native);QCOMPARE(errorFor([&]{projectcodec::encodeWeb(reopened.snapshot());}),QString("UNREPRESENTABLE_WEB_NUMBER"));QCOMPARE(projectcodec::encode(reopened.snapshot()),native);}
 void flagsAndRootClassification(){auto root=object();auto entities=root["territorialEntities"].toArray();auto row=entities[0].toObject(),properties=row["properties"].toObject(),metadata=properties["metadata"].toObject();metadata["flagDataUrl"]=QJsonValue::Null;properties["metadata"]=metadata;row["properties"]=properties;entities[0]=row;root["territorialEntities"]=entities;auto candidate=webimport::prepare(bytes(root));QCOMPARE(candidate.countries,2);QCOMPARE(candidate.subunits,1);QCOMPARE(candidate.regions,1);QVERIFY(candidate.document.symbols.at(territorialRef("A")).policy==FlagPolicy::None);}
 void nestedAndRetained(){auto candidate=webimport::prepare(full());QCOMPARE(staticParentRelation(candidate.document,"B").parentId,std::string("A"));QVERIFY(staticParentRelation(candidate.document,"R").parentId.empty());QCOMPARE(candidate.document.timelineRecords.parentRelations.size(),std::size_t(4));}
 void malformedKnownContainersAreRejected(){for(const auto* key:{"territorialEntities","timelineRecords","geometries","labels","hydroEdits","genericFeatures","distributionLayers","distributionEntries","labelSettings","distributionSettings","layerVisibility","itemVisibility","layerPresentation"}){auto root=object();root[key]=42;QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}}
 void unknownModelFieldsReceivePreservationBarrier(){auto root=object();auto model=root["territorialModel"].toObject();model["future"]=true;root["territorialModel"]=model;QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);root=object();auto entities=root["territorialEntities"].toArray();auto row=entities[0].toObject(),p=row["properties"].toObject();p["sovereignId"]="C";row["properties"]=p;entities[0]=row;root["territorialEntities"]=entities;QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}
 void distributionIndependentSharesAndReferences(){auto root=object();root["distributionLayers"]=QJsonArray{distributionLayer()};auto first=distributionEntry(),second=first;first["value"]=-50;second["id"]="00000000-0000-4000-8000-000000000013";second["value"]=3000;root["distributionEntries"]=QJsonArray{first,second};auto candidate=webimport::prepare(bytes(root));QCOMPARE(candidate.document.distributionEntries.size(),std::size_t(2));QCOMPARE(candidate.document.distributionEntries[0].value,-50.);second["territorialUnitId"]="missing";root["distributionEntries"]=QJsonArray{second};QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}
 void escapedDuplicatesDepthAndExtraOrdinates(){QVERIFY(errorFor([]{webimport::prepare(R"({"x":1,"\u0078":2})");}).contains("DUPLICATE_KEY"));QByteArray nested(130,'[');nested+="null";nested+=QByteArray(130,']');QVERIFY_EXCEPTION_THROWN(webimport::prepare(nested),std::invalid_argument);}
 void holesAndMultiPolygonCoordinatesAreUnchanged(){auto candidate=webimport::prepare(full());const auto shape=candidate.document.geometries.get(staticGeometryBinding(candidate.document,"A").geometryRef);QCOMPARE(shape->polygons.size(),std::size_t(3));QCOMPARE(shape->polygons.front().size(),std::size_t(2));QCOMPARE(shape->polygons[2][0][1].x,-179.);}
 void invalidRetainedSourceContractIsRejected(){auto root=object();root["labels"]=QJsonArray{QJsonObject{{"id","00000000-0000-4000-8000-000000000020"},{"name","City"},{"kind","city"},{"notes",""},{"coordinates",QJsonArray{1,2}},{"territorialUnitId","A"},{"source",QJsonObject{{"schemaVersion",2}}}}};QVERIFY_EXCEPTION_THROWN(webimport::prepare(bytes(root)),std::invalid_argument);}
 void cancelled(){QVERIFY(errorFor([]{webimport::prepare(full(),[]{return true;});}).startsWith("CANCELLED"));}
};
QTEST_GUILESS_MAIN(WebImportTests)
#include "web_import_tests.moc"
