// Actual Chromium collection is intentionally unavailable outside exact-commit CI.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {gzipSync} from 'node:zlib';
import {createLifecycleSuite,verifyLifecycleSuite,verifyLifecycleCI,verifyCommittedHarness,verifyLifecycleReport,captureBinding,runtimePin,limits} from './suite.mjs';
import {pendingContextOptions,exportPendingRow} from '../m977-pending-input/browser-runner.mjs';
export async function browserCase({suite,caseId,baseUrl}){
 const require=(v,m)=>{if(!v)throw Error(m);};require(typeof process==='undefined'&&typeof document==='object'&&typeof Worker==='function','actual browser required');
 const digest=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(v=>v.toString(16).padStart(2,'0')).join('');const bundle=suite.bundle,definition=bundle.corpus.cases.find(d=>d.id===caseId);require(definition,'declared case');
 const sourceHashes={},evidenceHashes={};for(const [p,s]of Object.entries(bundle.sources)){const response=await fetch(new URL(p,baseUrl));require(response.ok,'source missing '+p);sourceHashes[p]=await digest(await response.text());require(sourceHashes[p]===await digest(s),'source bytes mismatch '+p);}for(const [p,s]of Object.entries(bundle.evidenceSources))evidenceHashes[p]=await digest(s);
 require(await digest(suite.runtime.source)===suite.runtime.sha256,'runtime bytes mismatch');
 for(const name of ['polygon-clipping.min.js','d3.min.js'])await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('assets/js/vendor/'+name,baseUrl);s.onload=resolve;s.onerror=reject;document.head.append(s);});
 await import(new URL('assets/js/modules/polygon-geometry.js',baseUrl));const modules=await Promise.all(bundle.entrypoints.map(n=>import(new URL('assets/js/modules/'+n+'.js',baseUrl))));const api={...Object.assign({},...modules),...globalThis.PandoLabPolygonGeometry,d3:globalThis.d3,clipper:globalThis.polygonClipping};
 const runtime=(0,eval)(suite.runtime.source),loaded={api,bundle,evidenceSources:bundle.evidenceSources,runtime:runtime.base,selectionRuntime:runtime.base.selectionRuntime,createWorker:()=>new Worker(new URL('assets/js/workers/map-edit-worker.js',baseUrl))};
 const context={case:caseId,viewport:{width:innerWidth,height:innerHeight},node:typeof process!=='undefined',document:typeof document==='object',worker:typeof Worker==='function',userAgent:navigator.userAgent,devicePixelRatio,hasTouch:navigator.maxTouchPoints>0};
 return {state:'complete',identity:suite.identity,sourceHashes,evidenceHashes,context,observation:await runtime.run(loaded,definition,bundle.corpus)};
}
export function createLifecyclePage(suite,caseId){verifyLifecycleSuite(suite);assert.ok(suite.bundle.corpus.cases.some(d=>d.id===caseId));const encoded=gzipSync(JSON.stringify(suite),{level:9,mtime:0}).toString('base64');return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Pending-input lifecycle observations</title><script type="module">try{const suite=JSON.parse(await new Response(new Blob([Uint8Array.from(atob('${encoded}'),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip'))).text());globalThis.__m977PendingRow=await (${browserCase.toString()})({suite,caseId:${JSON.stringify(caseId)},baseUrl:new URL('/production/',location.href)});globalThis.__m977PendingSummary={state:'complete'};}catch(e){globalThis.__m977PendingSummary={state:'failed',error:String(e),stack:e.stack};}</script>`;}
async function main(){
 assert.equal(process.env.GITHUB_ACTIONS,'true','Actual lifecycle browser capture requires separately authorized exact-commit CI');const root=fileURLToPath(new URL('../../',import.meta.url)),head=execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim();verifyLifecycleCI(process.env,head);const suite=createLifecycleSuite({commit:head,runId:process.env.GITHUB_RUN_ID});verifyCommittedHarness(suite);
 const output=process.argv[2];assert.ok(output);assert.equal(fs.existsSync(output),false,'fresh capture directory required');const require=createRequire(new URL('../m97/river/browser/package.json',import.meta.url)),{chromium}=require('@playwright/test'),playwright=require('@playwright/test/package.json').version;const pin=JSON.parse(fs.readFileSync(path.join(path.dirname(require.resolve('playwright-core/package.json')),'browsers.json'))).browsers.find(b=>b.name==='chromium');assert.equal(playwright,runtimePin.playwright);assert.equal(pin.revision,runtimePin.revision);assert.equal(pin.browserVersion,runtimePin.chromium);
 fs.mkdirSync(output,{recursive:true});const suiteText=JSON.stringify(suite);fs.writeFileSync(path.join(output,'suite.json.gz'),gzipSync(suiteText,{level:9,mtime:0}));
 const pages=new Map(suite.bundle.corpus.cases.map(d=>['/case/'+d.id,createLifecyclePage(suite,d.id)]));const server=http.createServer((req,res)=>{if(pages.has(req.url)){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(pages.get(req.url));}const p=req.url?.startsWith('/production/')?req.url.slice(12):null;if(!p||!Object.hasOwn(suite.bundle.sources,p)){res.writeHead(404);return res.end();}res.setHeader('Content-Type','text/javascript');res.end(suite.bundle.sources[p]);});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});let browser;
 try{browser=await chromium.launch({headless:true});assert.equal(browser.version(),runtimePin.chromium);const cdp=await (await browser.newBrowserCDPSession()).send('Browser.getVersion');assert.equal(cdp.jsVersion,runtimePin.v8);const rows=[];
  for(const d of suite.bundle.corpus.cases){const context=await browser.newContext(pendingContextOptions(d.profile));try{const page=await context.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/case/'+d.id);await page.waitForFunction(()=>['complete','failed'].includes(globalThis.__m977PendingSummary?.state),{},{timeout:180000});const summary=await page.evaluate(()=>globalThis.__m977PendingSummary);assert.equal(summary.state,'complete',JSON.stringify(summary));const dest=path.join(output,d.id+'.json');await exportPendingRow(page,dest);const row=JSON.parse(fs.readFileSync(dest));assert.deepEqual(row.identity,suite.identity);rows.push(row);}finally{await context.close();}}
  for(const row of rows){assert.deepEqual(row.sourceHashes,rows[0].sourceHashes);assert.deepEqual(row.evidenceHashes,rows[0].evidenceHashes);}
  const report=verifyLifecycleReport(suite,{schema:'pando-m977-actual-chromium-pending-lifecycle',version:1,state:'complete',identity:suite.identity,limits,sourceHashes:rows[0].sourceHashes,evidenceHashes:rows[0].evidenceHashes,runtime:{collector:'actual-chromium',playwright,browserVersion:browser.version(),chromiumRevision:pin.revision,cdp,ci:{commit:head,runId:process.env.GITHUB_RUN_ID}},contexts:rows.map(r=>r.context),cases:rows.map(r=>r.observation)});const text=JSON.stringify(report);fs.writeFileSync(path.join(output,'browser-report.json'),text);fs.writeFileSync(path.join(output,'capture-verification.json'),JSON.stringify(captureBinding(suiteText,text),null,2));console.log(JSON.stringify({cases:2,stages:58,rawParity:false}));
 }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e);process.exitCode=1;});
