import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {gunzipSync} from 'node:zlib';import {execFileSync} from 'node:child_process';
import {verifyCapture,verifyLifecycleCI,verifyCommittedHarness} from './suite.mjs';import {sha256} from './sources.mjs';import {collectNativeCapture,compareLifecycle} from './compare.mjs';
export function verifyNativeIdentity(identity,suite,binary){assert.deepEqual(Object.keys(identity).sort(),['commit','runId','sha256','qt'].sort());assert.equal(identity.commit,suite.commit);assert.equal(identity.runId,suite.runId);assert.equal(identity.qt,'6.8.3');assert.equal(identity.sha256,sha256(fs.readFileSync(binary)),'actual native executable identity');}
export function runLifecycleGate({capture,nativeBinary,nativeIdentity,output,env=process.env}){
 const root=fileURLToPath(new URL('../../',import.meta.url)),head=execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim();verifyLifecycleCI(env,head);
 const suiteText=gunzipSync(fs.readFileSync(path.join(capture,'suite.json.gz'))).toString('utf8'),reportText=fs.readFileSync(path.join(capture,'browser-report.json'),'utf8'),binding=JSON.parse(fs.readFileSync(path.join(capture,'capture-verification.json'))),suite=JSON.parse(suiteText);assert.equal(suite.commit,head);assert.equal(suite.runId,env.GITHUB_RUN_ID);verifyCommittedHarness(suite);
 const web=verifyCapture(suiteText,reportText,binding);verifyNativeIdentity(nativeIdentity,suite,nativeBinary);const collected=collectNativeCapture(nativeBinary,suite.bundle),native=collected.report;verifyNativeIdentity(nativeIdentity,suite,nativeBinary);
 const comparison=compareLifecycle(suite.bundle,web,native);comparison.actualBrowser=true;comparison.identity=suite.identity;comparison.native=nativeIdentity;comparison.capture=binding;comparison.rawEvidence={browserSha256:sha256(reportText),nativeSha256:collected.rawSha256,nativeBytes:collected.rawBytes};
 assert.equal(fs.existsSync(output),false,'fresh gate output required');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'native.json'),collected.raw);fs.writeFileSync(path.join(output,'native-stderr.log'),collected.stderr);fs.writeFileSync(path.join(output,'comparison.json'),JSON.stringify(comparison,null,2));return comparison;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const [capture,nativeBinary,identityFile,output]=process.argv.slice(2);assert.ok(capture&&nativeBinary&&identityFile&&output,'Usage: gate capture-dir native-binary native-identity.json fresh-output-dir');const r=runLifecycleGate({capture,nativeBinary,nativeIdentity:JSON.parse(fs.readFileSync(identityFile)),output});console.log(JSON.stringify({cases:r.cases.length,stages:58,functionalLifecycleContractsPassed:true,rawParity:false,actualBrowser:true}));
}
