import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {readLifecycleSources,verifyLifecycleSources,sha256} from './sources.mjs';
import {runPendingLifecycleCase} from './runtime.mjs';
import {verifyWebLifecycleCase} from './contract.mjs';
import {sourceHistoryRuntimeSource} from '../m974-snap-boundary/source-history-suite.mjs';
import {installExchangeInput,exchangeCheckpoint,exchangeSerializer,wireExchangeHydro} from '../m975-model-exchange/runtime.mjs';
import {runtimePin as approvedRuntimePin} from '../m97/river/suite.mjs';
export const runtimePin=Object.freeze({...approvedRuntimePin});
export const limits=Object.freeze({rawParity:false,fullDOM:false,physicalTouch:false,gpu:false,fullStartupActivation:false,preparationFailure:false,workerCPUExecutionPhase:false,heldResultIsWorkerComplete:true,fullRawWebHistoryEquality:false,nativeFullRawHistoryEquality:true,webHistoryScope:'existing model-exchange documentKeys; exact seven raw normalization deltas separately retained'});
const directory=fileURLToPath(new URL('./',import.meta.url)),root=path.resolve(directory,'../..');
export function lifecycleRuntimeSource(){return `(()=>{const base=${sourceHistoryRuntimeSource()};${installExchangeInput.toString()};${exchangeSerializer.toString()};${exchangeCheckpoint.toString()};${wireExchangeHydro.toString()};return {base,run:${runPendingLifecycleCase.toString()}};})()`;}
export function harnessHashes(){
 const queue=['sources.mjs','runtime.mjs','contract.mjs','suite.mjs','browser-runner.mjs','compare.mjs','gate.mjs','node-runner.mjs','../../tests/m977_pending_lifecycle_probe.cpp','../../app/CMakeLists.txt','../../.github/workflows/m977-pending-lifecycle.yml','../m97/river/browser/package.json','../m97/river/browser/package-lock.json','corpus.json','runtime.test.mjs','contract.test.mjs','native.test.mjs','suite.test.mjs','../../tests/m977-pending-lifecycle-integration.test.mjs','../m6-regression-audit.py','../../tests/m974_regression_gate_tests.py'].map(p=>path.resolve(directory,p)),seen=new Map();
 while(queue.length){const file=queue.pop();if(seen.has(file))continue;assert.ok(file.startsWith(root+path.sep));const raw=fs.readFileSync(file);seen.set(file,sha256(raw));if(file.endsWith('.mjs'))for(const m of raw.toString().matchAll(/(?:from\s*|import\s*(?:\(\s*)?|new\s+URL\(\s*)['"](\.{1,2}\/[A-Za-z0-9_./-]+\.mjs)['"]/g))queue.push(path.resolve(path.dirname(file),m[1]));}
 return Object.fromEntries([...seen].map(([file,hash])=>[path.relative(directory,file).split(path.sep).join('/'),hash]).sort(([a],[b])=>a.localeCompare(b)));
}
const identity=s=>({schema:s.schema,version:s.version,commit:s.commit,runId:s.runId,runtimePin,sourceSha256:sha256(JSON.stringify(s.bundle.sources)),evidenceSha256:sha256(JSON.stringify(s.bundle.evidenceSources)),sourceManifestSha256:sha256(JSON.stringify(s.bundle.manifest)),supplementSha256:sha256(JSON.stringify(s.bundle.supplement)),pendingAddendumSha256:sha256(JSON.stringify(s.bundle.pendingAddendum)),corpusSha256:s.bundle.corpusSha256,fixture:s.bundle.corpus.fixture,runtimeSha256:s.runtime.sha256,harnessFiles:s.harnessFiles,caseStages:s.bundle.corpus.cases.map(d=>({id:d.id,stages:d.stages})),limits});
export function createLifecycleSuite({commit,runId}){const source=lifecycleRuntimeSource(),s={schema:'pando-m977-pending-lifecycle-suite',version:1,commit,runId,bundle:readLifecycleSources(),runtime:{source,sha256:sha256(source)},harnessFiles:harnessHashes()};s.identity=identity(s);return verifyLifecycleSuite(s);}
export function verifyLifecycleSuite(s){
 assert.deepEqual(Object.keys(s).sort(),['schema','version','commit','runId','bundle','runtime','harnessFiles','identity'].sort());assert.equal(s.schema,'pando-m977-pending-lifecycle-suite');assert.equal(s.version,1);assert.match(s.commit||'',/^[a-f0-9]{40}$/);assert.match(s.runId||'',/^\d+$/);verifyLifecycleSources(s.bundle);const source=lifecycleRuntimeSource();assert.deepEqual(s.runtime,{source,sha256:sha256(source)});assert.deepEqual(s.harnessFiles,harnessHashes());assert.deepEqual(s.identity,identity(s));return s;
}
export function verifyLifecycleCI(env,head){assert.equal(env.GITHUB_ACTIONS,'true','Actual lifecycle browser capture requires separately authorized exact-commit CI');assert.match(env.GITHUB_SHA||'',/^[a-f0-9]{40}$/);assert.match(env.GITHUB_RUN_ID||'',/^\d+$/);assert.equal(head,env.GITHUB_SHA);}
export function verifyCommittedHarness(suite){execFileSync('git',['-C',root,'diff','--exit-code',suite.commit,'--']);for(const [name,hash]of Object.entries(suite.harnessFiles)){const rel=path.relative(root,path.resolve(directory,name)).split(path.sep).join('/');assert.equal(sha256(execFileSync('git',['-C',root,'show',suite.commit+':'+rel])),hash,'capture harness equals exact committed bytes '+rel);}assert.equal(sha256(execFileSync('git',['-C',root,'show',suite.commit+':'+suite.bundle.corpus.fixture.path])),suite.bundle.corpus.fixture.sha256);}
export function verifyLifecycleReport(suite,report){
 verifyLifecycleSuite(suite);assert.deepEqual(Object.keys(report).sort(),['schema','version','state','identity','limits','sourceHashes','evidenceHashes','runtime','contexts','cases'].sort());assert.equal(report.schema,'pando-m977-actual-chromium-pending-lifecycle');assert.equal(report.version,1);assert.equal(report.state,'complete');assert.deepEqual(report.identity,suite.identity);assert.deepEqual(report.limits,limits);
 assert.deepEqual(report.sourceHashes,Object.fromEntries(Object.entries(suite.bundle.sources).map(([p,s])=>[p,sha256(s)])));assert.deepEqual(report.evidenceHashes,Object.fromEntries(Object.entries(suite.bundle.evidenceSources).map(([p,s])=>[p,sha256(s)])));
 const r=report.runtime;assert.deepEqual(Object.keys(r).sort(),['collector','playwright','browserVersion','chromiumRevision','cdp','ci'].sort());assert.equal(r.collector,'actual-chromium');assert.equal(r.playwright,runtimePin.playwright);assert.equal(r.browserVersion,runtimePin.chromium);assert.equal(r.chromiumRevision,runtimePin.revision);assert.equal(r.cdp.jsVersion,runtimePin.v8);assert.ok(['Chrome/','HeadlessChrome/'].some(p=>r.cdp.product===p+runtimePin.chromium));assert.deepEqual(r.ci,{commit:suite.commit,runId:suite.runId});
 assert.deepEqual(report.contexts.map(c=>c.case),suite.bundle.corpus.cases.map(d=>d.id));assert.deepEqual(report.cases.map(c=>c.case),suite.bundle.corpus.cases.map(d=>d.id));
 for(const [i,d]of suite.bundle.corpus.cases.entries()){const c=report.contexts[i];assert.deepEqual(c.viewport,{width:d.profile.width,height:d.profile.height});assert.equal(c.node,false);assert.equal(c.document,true);assert.equal(c.worker,true);assert.equal(c.devicePixelRatio,1);assert.equal(c.hasTouch,d.profile.pointerType==='touch');assert.ok(c.userAgent.includes('Chrome/'+runtimePin.chromium));verifyWebLifecycleCase(suite.bundle,d,report.cases[i]);}return report;
}
export function captureBinding(suiteText,reportText){const s=JSON.parse(suiteText),r=verifyLifecycleReport(s,JSON.parse(reportText));return {schema:'pando-m977-pending-lifecycle-capture',version:1,identity:s.identity,suiteSha256:sha256(suiteText),suiteBytes:Buffer.byteLength(suiteText),reportSha256:sha256(reportText),reportBytes:Buffer.byteLength(reportText),cases:r.cases.length,stages:58,rawParity:false};}
export function verifyCapture(suiteText,reportText,binding){assert.deepEqual(binding,captureBinding(suiteText,reportText),'complete decompressed capture bytes');return JSON.parse(reportText);}
