import assert from 'node:assert/strict';import test from 'node:test';
import {createLifecycleSuite,verifyLifecycleSuite,verifyLifecycleCI,runtimePin} from './suite.mjs';
test('suite binds independent corpus fixture source harness and runtime identity',()=>{const s=createLifecycleSuite({commit:'a'.repeat(40),runId:'123'});verifyLifecycleSuite(s);assert.equal(s.bundle.corpus.cases.length,2);assert.equal(runtimePin.playwright,'1.62.1');for(const mutate of [s=>s.bundle.corpus.cases.pop(),s=>s.bundle.fixtureRaw+=' ',s=>s.runtime.source+=' ',s=>delete s.harnessFiles['runtime.mjs'],s=>s.commit='main',s=>s.bundle.sources['assets/js/modules/tool-controller.js']+=' ',s=>s.identity.runId='0']){const bad=structuredClone(s);mutate(bad);assert.throws(()=>verifyLifecycleSuite(bad));}});
test('browser execution refuses non-CI or wrong exact commit',()=>{assert.throws(()=>verifyLifecycleCI({},'a'.repeat(40)));assert.throws(()=>verifyLifecycleCI({GITHUB_ACTIONS:'true',GITHUB_SHA:'a'.repeat(40),GITHUB_RUN_ID:'123'},'b'.repeat(40)));});

import {loadLifecycleSources,sha256} from './sources.mjs';
import {verifyLifecycleReport,captureBinding,verifyCapture,lifecycleRuntimeSource,limits} from './suite.mjs';
import {compareLifecycle} from './compare.mjs';
import {verifyNativeIdentity} from './gate.mjs';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
test('browser-portable runtime and capture validator bind every source, context and raw byte',async()=>{
 const loaded=await loadLifecycleSources(),suite=createLifecycleSuite({commit:'a'.repeat(40),runId:'123'});let cases=[];
 try{const executable=(0,eval)(lifecycleRuntimeSource());for(const d of suite.bundle.corpus.cases)cases.push(await executable.run({...loaded,runtime:executable.base,selectionRuntime:executable.base.selectionRuntime},d,suite.bundle.corpus));}finally{loaded.cleanup();}
 // Synthetic transport metadata tests validator integrity, never browser execution.
 const report={schema:'pando-m977-actual-chromium-pending-lifecycle',version:1,state:'complete',identity:suite.identity,limits,sourceHashes:Object.fromEntries(Object.entries(suite.bundle.sources).map(([p,s])=>[p,sha256(s)])),evidenceHashes:Object.fromEntries(Object.entries(suite.bundle.evidenceSources).map(([p,s])=>[p,sha256(s)])),runtime:{collector:'actual-chromium',playwright:runtimePin.playwright,browserVersion:runtimePin.chromium,chromiumRevision:runtimePin.revision,cdp:{jsVersion:runtimePin.v8,product:'Chrome/'+runtimePin.chromium},ci:{commit:suite.commit,runId:suite.runId}},contexts:suite.bundle.corpus.cases.map(d=>({case:d.id,viewport:{width:d.profile.width,height:d.profile.height},node:false,document:true,worker:true,devicePixelRatio:1,hasTouch:d.profile.pointerType==='touch',userAgent:'Chrome/'+runtimePin.chromium})),cases};
 verifyLifecycleReport(suite,report);
 for(const mutate of [r=>r.cases.pop(),r=>delete r.cases[0].stages.retryReview,r=>r.schema='pando-m977-node-pending-lifecycle',r=>r.runtime.collector='node',r=>r.runtime.cdp.jsVersion='fake',r=>r.runtime.ci.commit='b'.repeat(40),r=>r.contexts[1].hasTouch=false,r=>r.contexts[0].viewport.width=360,r=>r.contexts[0].node=true,r=>r.sourceHashes['assets/js/modules/tool-controller.js']='0'.repeat(64),r=>r.evidenceHashes={},r=>r.identity={...r.identity,corpusSha256:'0'.repeat(64)}]){const bad=structuredClone(report);mutate(bad);assert.throws(()=>verifyLifecycleReport(suite,bad));}
 const st=JSON.stringify(suite),rt=JSON.stringify(report),binding=captureBinding(st,rt);verifyCapture(st,rt,binding);assert.throws(()=>verifyCapture(st,rt+' ',binding));assert.throws(()=>verifyCapture(st+' ',rt,binding));
});
test('native identity requires exact binary, commit, run and Qt',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'m977-identity-'));try{const file=path.join(dir,'binary');fs.writeFileSync(file,'contract-test');const suite={commit:'a'.repeat(40),runId:'123'},identity={...suite,qt:'6.8.3',sha256:sha256('contract-test')};verifyNativeIdentity(identity,suite,file);for(const k of ['commit','runId','qt','sha256'])assert.throws(()=>verifyNativeIdentity({...identity,[k]:'wrong'},suite,file));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
