// Actual Chromium capture is available only on an authorized exact-SHA GitHub run.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {execFileSync,spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {gzipSync} from 'node:zlib';
import {createExchangeSuite,verifyExchangeSuite,verifyBrowserReport,nativeRequest,browserExchangeStages,verifyEditEffect,runtimePin,observationLimits} from './suite.mjs';
import {sha256,rawRecord,verifyRawRecord,verifyCI,assertExchangeEqual,assertNativeExchangeEqual,permittedNormalizations} from './contract.mjs';
import {verifyNativeInputObservations,verifyNativeEditStages} from './native-contract.mjs';
import {writeBoundedJsonArtifact} from '../m97/river/browser/report-transfer.mjs';
export function verifyNativeRuntime(directory,commit){
 assert.equal(fs.readFileSync(path.join(directory,'COMMIT'),'utf8').trim(),commit,'native artifact exact application COMMIT');assert.equal(fs.readFileSync(path.join(directory,'QT_VERSION'),'utf8').trim(),'6.8.3','approved native Qt runtime');
 const file='m975_model_exchange_probe',rows=fs.readFileSync(path.join(directory,'SHA256SUMS'),'utf8').trim().split('\n').filter(Boolean).map(line=>{const m=line.match(/^([a-f0-9]{64}) [ *](.+)$/);assert.ok(m,'valid SHA256SUMS row');return {sha256:m[1],file:m[2]};}),matches=rows.filter(r=>r.file===file||r.file==='./'+file);assert.equal(matches.length,1,'exact native probe SHA inventory');
 const bytes=fs.readFileSync(path.join(directory,file));assert.equal(sha256(bytes),matches[0].sha256,'native probe bytes match authenticated artifact');return {commit,sha256:matches[0].sha256,bytes:bytes.length,qtVersion:'6.8.3'};
}
export async function runBrowserExchange({suite,baseUrl}){
 const hash=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join(''),require=(v,m)=>{if(!v)throw Error(m);},sourceHashes={},evidenceHashes={};
 for(const [name,source]of Object.entries(suite.sources)){const response=await fetch(new URL(name,baseUrl));require(response.ok,'missing pinned source '+name);const actual=await response.text();sourceHashes[name]=await hash(actual);require(sourceHashes[name]===await hash(source),'source SHA '+name);}
 for(const [name,source]of Object.entries(suite.evidenceSources))evidenceHashes[name]=await hash(source);
 require(await hash(suite.runtime.source)===suite.runtime.sha256,'runtime SHA');
 for(const name of ['polygon-clipping.min.js','d3.min.js'])await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=new URL('assets/js/vendor/'+name,baseUrl);script.onload=resolve;script.onerror=reject;document.head.append(script);});
 await import(new URL('assets/js/modules/polygon-geometry.js',baseUrl));const modules=await Promise.all(suite.entrypoints.map(name=>import(new URL('assets/js/modules/'+name+'.js',baseUrl)))),api={...Object.assign({},...modules),...globalThis.PandoLabPolygonGeometry,d3:globalThis.d3,clipper:globalThis.polygonClipping},runtime=(0,eval)(suite.runtime.source);
 require(typeof api.createProjectSerializer==='function','actual serializer export');require(typeof api.prepareProjectForStorage==='function'&&typeof api.prepareProjectForActivation==='function','actual reader exports');
 const loaded=globalThis.__m975Loaded={api,runtime,selectionRuntime:runtime.selectionRuntime,sourceTexts:suite.sources,evidenceSources:suite.evidenceSources,createWorker:()=>new Worker(new URL('assets/js/workers/map-edit-worker.js',baseUrl))},cases=[];
 for(const definition of suite.cases)cases.push(await runtime.runExchangeCase(loaded,structuredClone(definition)));
 return {schema:'pando-m975-actual-chromium-model-exchange',version:1,state:'complete',identity:suite.identity,sourceHashes,evidenceHashes,runtime:{userAgent:navigator.userAgent},cases};
}
export function createExchangePage(suite){verifyExchangeSuite(suite);const bytes=gzipSync(JSON.stringify(suite),{level:9,mtime:0}).toString('base64');return `<!doctype html><meta charset="utf-8"><title>M9.7.5 actual browser model exchange</title><pre id="status">Running</pre><script type="module">try{const suite=JSON.parse(await new Response(new Blob([Uint8Array.from(atob('${bytes}'),c=>c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip'))).text());globalThis.__m975Report=await (${runBrowserExchange.toString()})({suite,baseUrl:new URL('/production/',location.href)});globalThis.__m975Summary={state:'complete',cases:globalThis.__m975Report.cases.length};}catch(error){globalThis.__m975Summary={state:'failed',error:String(error),stack:error.stack};}document.querySelector('#status').textContent=JSON.stringify(globalThis.__m975Summary,null,2);</script>`;}
async function exportBrowserValue(page,destination,getValue,arg){
 const metadata=await page.evaluate(async({source,arg})=>{const value=await (0,eval)('('+source+')')(arg),raw=globalThis.__m975Transfer=typeof value==='string'?value:JSON.stringify(value),bytes=new TextEncoder().encode(raw);return {characters:raw.length,bytes:bytes.length,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('')};},{source:getValue.toString(),arg});
 try{return await writeBoundedJsonArtifact(metadata,request=>page.evaluate(({offset,maximum})=>{const raw=globalThis.__m975Transfer;let next=Math.min(offset+maximum,raw.length);if(next<raw.length&&raw.charCodeAt(next-1)>=0xd800&&raw.charCodeAt(next-1)<=0xdbff)next--;return {offset,text:raw.slice(offset,next),next};},request),destination);}finally{await page.evaluate(()=>delete globalThis.__m975Transfer);}
}
function verifyEnvelope(row,label){assert.ok(row&&typeof row.base64==='string',label+' bytes');const bytes=Buffer.from(row.base64,'base64');assert.equal(bytes.length,row.size,label+' size');assert.equal(sha256(bytes),row.sha256,label+' SHA');if(Object.hasOwn(row,'raw'))assert.equal(bytes.toString('utf8'),row.raw,label+' exact raw bytes');return bytes;}
export function verifyNativeResult(result,request,input){
 assert.equal(result.runtime?.compiledQt,'6.8.3','actual compiled Qt');assert.equal(result.runtime?.qt,'6.8.3','actual loaded Qt');assert.equal(result.schema,'pando-m975-native-exchange-result');assert.equal(result.version,1);assert.equal(result.id,request.id);assert.equal(result.mode,request.mode);
 assert.equal(verifyEnvelope(result.input,'native input').toString('utf8'),input);assert.equal(result.input.sha256,request.inputSha256);assert.equal(result.sourcePreserved,true,'source QFile preserved after all operations');assert.deepEqual(verifyEnvelope(result.inputAfter,'actual source QFile reread'),Buffer.from(input,'utf8'),'actual source QFile bytes unchanged');
 assert.deepEqual(result.stageOrder,request.expectedStages,'complete native stage order');assert.deepEqual(Object.keys(result.stages).sort(),[...request.expectedStages].sort(),'complete native stage inventory');
 assert.equal(result.actions.length,request.actions.length,'complete native public action count');for(const [i,action]of result.actions.entries()){assert.equal(action.op,request.actions[i].op,'native ordered public action');assert.equal(action.accepted,request.actions[i].expectAccepted!==false,'native settled public action outcome');if(request.actions[i].stage)assert.equal(action.stage,request.actions[i].stage);}
 for(const [stage,row]of Object.entries(result.stages)){
  assert.equal(row.observed,true,'actual observed native stage '+stage);
  if(request.mode==='reject'){
   assert.equal(row.accepted,false);assert.equal(Object.hasOwn(row,'webFile'),false,'refused import publishes no web output');assert.equal(row.refusalPhase,'import');assert.ok(row.error.includes(request.expectedError));assert.equal(row.importOnly,true);assert.equal(row.publicationAttempted,false);assert.equal(row.projectOutputPublished,false);
   for(const field of ['sourcePreserved','canonicalUnchanged','historyUnchanged'])assert.equal(row[field],true,'native import refusal '+field);for(const unsupported of ['destinationUnchanged','sentinelUnchanged','newDestinationAbsent'])assert.equal(Object.hasOwn(row,unsupported),false,'import-only refusal must not claim unexecuted publisher sentinel proof');continue;
  }
  if(stage==='activation-rejected'){for(const field of ['accepted','activationAccepted'])assert.equal(row[field],false);for(const field of ['canonicalUnchanged','historyUnchanged'])assert.equal(row[field],true);assert.ok(row.error);continue;}
  assert.deepEqual(verifyEnvelope(row.document,stage+' canonical'),verifyEnvelope(row.nativeFile,stage+' native QFile'),'actual native QFile matches canonical document '+stage);verifyEnvelope(row.webFile,stage+' web file');assert.equal(row.nativeFile.reopenEqual,true,'native QFile decoded exact save');
  if(request.mode==='edit'){const active=['preview','rejected'].includes(stage);assert.equal(row.nativeFile.saveMethod,active?'QFile-production-codec-after-controller-save-refusal':'EditorController.saveFile/openFile','stage-specific actual application persistence');assert.equal(row.nativeFile.saveAccepted,!active);if(active){assert.equal(row.nativeFile.activeSaveRefused,true);assert.equal(row.nativeFile.destinationUnchanged,true);assert.equal(row.nativeFile.codecFileRoundtrip,true);}}else{assert.equal(row.nativeFile.saveMethod,'QFile-production-codec','storage-only codec persistence');assert.equal(row.nativeFile.codecFileRoundtrip,true);}
 }
 verifyNativeInputObservations(result,request);verifyNativeEditStages(result,request);
 if(request.mode==='edit'){
  for(const name of ['preview','cancel','rejected'])if(result.stages[name]){assert.equal(result.stages[name].document.base64,result.stages.before.document.base64,'canonical native '+name+' is atomic');assert.deepEqual(result.stages[name].history,result.stages.before.history,'native '+name+' history unchanged');}
  for(const [stage,row]of Object.entries(result.stages)){const expected=stage==='confirm'||stage==='redo'?[true,false]:stage==='undo'?[false,true]:[false,false];assert.deepEqual([row.history?.canUndo,row.history?.canRedo],expected,'native public history state '+stage);}
  const documentKeys=['territorialEntities','sourceInfo','labels','genericFeatures','hydroEdits','timelineRecords','geometries','distributionLayers','distributionEntries'];const content=stage=>{const p=JSON.parse(result.stages[stage].webFile.raw);return Object.fromEntries(documentKeys.map(key=>[key,p[key]]));};if(result.stages.undo)assert.deepEqual(content('undo'),content('before'),'native Undo identity/archive/content/ref restoration');if(result.stages.redo)assert.deepEqual(content('redo'),content('confirm'),'native Redo identity/archive/content/ref restoration');
  if(result.stages.confirm)assert.notEqual(result.stages.confirm.document.base64,result.stages.before.document.base64,'native real edit changes canonical document');
 }
 return result;
}
function invokeNative(binary,input,request,directory){fs.mkdirSync(directory,{recursive:true});const file=path.join(directory,'input.json'),req=path.join(directory,'request.json');fs.writeFileSync(file,input);fs.writeFileSync(req,JSON.stringify(request,null,2)+'\n');const result=spawnSync(binary,[file,req,directory],{encoding:'utf8',timeout:180000,maxBuffer:64*1024*1024,env:{...process.env,QT_QPA_PLATFORM:'offscreen'}});fs.writeFileSync(path.join(directory,'stdout.json'),result.stdout||'');fs.writeFileSync(path.join(directory,'stderr.txt'),result.stderr||'');assert.equal(result.status,0,request.id+': '+(result.error||result.stderr||result.stdout));const parsed=verifyNativeResult(JSON.parse(result.stdout),request,input);fs.writeFileSync(path.join(directory,'verified-result.json'),JSON.stringify(parsed,null,2)+'\n');return parsed;}
async function browserReopen(page,raw,storageOnly,destination){await exportBrowserValue(page,destination,async({raw,storageOnly})=>globalThis.__m975Loaded.runtime.reopenExchange(globalThis.__m975Loaded,raw,{storageOnly}),{raw,storageOnly});const result=JSON.parse(fs.readFileSync(destination,'utf8'));verifyRawRecord(result.save);assert.equal(result.reader.storage,true);assert.equal(result.reader.activation,!storageOnly);return result;}
async function main(){
 // This guard precedes output writes, loading Playwright or launching a browser.
 assert.equal(process.env.GITHUB_ACTIONS,'true','Actual browser capture requires authorized exact-commit GitHub CI');
 const root=fileURLToPath(new URL('../../',import.meta.url)),head=execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim();verifyCI(process.env,head);
 const [runtimeDirectory,output]=process.argv.slice(2);assert.ok(runtimeDirectory&&output,'usage: browser-runner.mjs <native-runtime-dir> <evidence-dir>');const native=verifyNativeRuntime(runtimeDirectory,head),binary=path.resolve(runtimeDirectory,'m975_model_exchange_probe'),suite=createExchangeSuite({commit:head,runId:process.env.GITHUB_RUN_ID,native}),html=createExchangePage(suite);
 fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'suite.json.gz'),gzipSync(JSON.stringify(suite),{level:9,mtime:0}));fs.writeFileSync(path.join(output,'suite-pin.json'),JSON.stringify({identity:suite.identity,sha256:sha256(JSON.stringify(suite)),bytes:Buffer.byteLength(JSON.stringify(suite))},null,2));
 const require=createRequire(new URL('../m97/river/browser/package.json',import.meta.url)),{chromium}=require('@playwright/test'),playwright=require('@playwright/test/package.json').version,pins=JSON.parse(fs.readFileSync(path.join(path.dirname(require.resolve('playwright-core/package.json')),'browsers.json'))),pin=pins.browsers.find(p=>p.name==='chromium');assert.equal(playwright,runtimePin.playwright);assert.equal(pin.revision,runtimePin.revision);assert.equal(pin.browserVersion,runtimePin.chromium);
 const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);return;}const name=req.url?.startsWith('/production/')?req.url.slice(12):null;if(!name||!Object.hasOwn(suite.sources,name)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type','text/javascript; charset=utf-8');res.end(suite.sources[name]);});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});let browser;
 try{
  browser=await chromium.launch({headless:true});const page=await browser.newPage(),cdp=await page.context().newCDPSession(page),version=await cdp.send('Browser.getVersion');assert.equal(browser.version(),runtimePin.chromium);assert.equal(version.jsVersion,runtimePin.v8);fs.writeFileSync(path.join(output,'cdp-runtime.json'),JSON.stringify(version,null,2));
  await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>['complete','failed'].includes(globalThis.__m975Summary?.state),{},{timeout:240000});const summary=await page.evaluate(()=>globalThis.__m975Summary);fs.writeFileSync(path.join(output,'browser-summary.json'),JSON.stringify(summary,null,2));assert.equal(summary.state,'complete',JSON.stringify(summary));
  const transfer=await exportBrowserValue(page,path.join(output,'browser-report.json'),runtime=>{globalThis.__m975Report.runtime={...globalThis.__m975Report.runtime,...runtime};return globalThis.__m975Report;},{playwright,browserVersion:browser.version(),chromiumRevision:pin.revision,cdp:version});fs.writeFileSync(path.join(output,'report-transfer.json'),JSON.stringify(transfer,null,2));const report=verifyBrowserReport(suite,JSON.parse(fs.readFileSync(path.join(output,'browser-report.json'),'utf8'))),exchanges=[],rejections=[];
  for(const [index,definition]of suite.cases.entries()){
   const browserCase=report.cases[index],storageOnly=definition.operation==='storage';
   const browserCheckpoints={...browserCase.stages,...(browserCase.controls.delta?{'full-autosave':{save:browserCase.controls.delta.full,expected:browserCase.controls.delta.fullStored},'delta-recovered':{save:browserCase.controls.delta.recovered}}:{})};
   for(const [stage,checkpoint]of Object.entries(browserCheckpoints)){
    const id=definition.id+'-web-'+stage,directory=path.join(output,id),request=nativeRequest(definition,{codec:true,id,sha:checkpoint.save.sha256}),result=invokeNative(binary,checkpoint.save.raw,request,directory),web=result.stages.storage.webFile.raw;
    assertExchangeEqual(JSON.parse((checkpoint.expected||checkpoint.save).raw),JSON.parse(web),id+' browser→native full-file semantics');const reopened=await browserReopen(page,web,storageOnly,path.join(directory,'browser-reopened.json'));assertExchangeEqual(JSON.parse(web),JSON.parse(reopened.save.raw),id+' native→browser full-file semantics');exchanges.push({case:definition.id,direction:'browser-native-browser',stage,inputSha256:checkpoint.save.sha256,nativeSha256:result.stages.storage.nativeFile.sha256,webSha256:result.stages.storage.webFile.sha256,browserSha256:reopened.save.sha256});
   }
   if(browserCase.controls.delta){const raw=browserCase.controls.delta.file,id=definition.id+'-raw-delta-refusal',request={...nativeRequest(definition,{codec:true,id,sha:raw.sha256}),mode:'reject',expectedError:'BASE_DATA_REQUIRED',expectedStages:['rejected']};const rejected=invokeNative(binary,raw.raw,request,path.join(output,id));rejections.push({case:definition.id,inputSha256:raw.sha256,stage:rejected.stages.rejected});}
   const directory=path.join(output,definition.id+'-native-edits'),result=invokeNative(binary,definition.inputRaw,nativeRequest(definition),directory);
   if(definition.operation!=='storage'&&!definition.reject)verifyEditEffect(definition,JSON.parse(result.stages.before.webFile.raw),JSON.parse(result.stages.confirm.webFile.raw));
   for(const stage of result.stageOrder.filter(s=>s!=='activation-rejected')){
    const checkpoint=result.stages[stage],stageDirectory=path.join(directory,stage);fs.mkdirSync(stageDirectory,{recursive:true});const reopened=await browserReopen(page,checkpoint.webFile.raw,storageOnly,path.join(stageDirectory,'browser-reopened.json'));assertExchangeEqual(JSON.parse(checkpoint.webFile.raw),JSON.parse(reopened.save.raw),definition.id+' '+stage+' native→browser full-file semantics');
    const returned=invokeNative(binary,reopened.save.raw,nativeRequest(definition,{codec:true,id:definition.id+'-native-'+stage+'-return',sha:reopened.save.sha256}),path.join(stageDirectory,'native-return'));assertNativeExchangeEqual(JSON.parse(Buffer.from(checkpoint.document.base64,'base64').toString('utf8')),JSON.parse(Buffer.from(returned.stages.storage.document.base64,'base64').toString('utf8')),definition.id+' '+stage+' complete native GeometryRefs/archive/content return');assertExchangeEqual(JSON.parse(checkpoint.webFile.raw),JSON.parse(returned.stages.storage.webFile.raw),definition.id+' '+stage+' browser→native full-file semantics');exchanges.push({case:definition.id,direction:'native-browser-native',stage,inputSha256:result.input.sha256,nativeSha256:checkpoint.nativeFile.sha256,webSha256:checkpoint.webFile.sha256,browserSha256:reopened.save.sha256,returnedNativeSha256:returned.stages.storage.nativeFile.sha256});
   }
  }
  const expected=suite.cases.flatMap(c=>[...browserExchangeStages(c).map(stage=>({case:c.id,direction:'browser-native-browser',stage})),...(c.operation==='storage'?['storage']:c.stages).map(stage=>({case:c.id,direction:'native-browser-native',stage}))]);assert.deepEqual(exchanges.map(({case:caseId,direction,stage})=>({case:caseId,direction,stage})),expected,'exact complete bidirectional exchange inventory');
  assert.deepEqual(rejections.map(r=>r.case),['m975-annex-full-recursive'],'exact raw delta refusal inventory');fs.writeFileSync(path.join(output,'rejection-observations.json'),JSON.stringify(rejections,null,2));fs.writeFileSync(path.join(output,'exchange-observations.json'),JSON.stringify(exchanges,null,2));const complete={schema:'pando-m975-model-exchange-capture-verification',version:1,state:'complete',passed:true,identity:suite.identity,cases:suite.cases.length,exchanges:exchanges.length,browserReportSha256:sha256(fs.readFileSync(path.join(output,'browser-report.json'))),permittedNormalizations,observationLimits};fs.writeFileSync(path.join(output,'capture-verification.json'),JSON.stringify(complete,null,2));console.log(JSON.stringify(complete));
 }catch(error){fs.writeFileSync(path.join(output,'failure.txt'),String(error)+'\n'+error.stack);throw error;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(error=>{console.error(error);process.exitCode=1;});
