import {editVerifierFixture} from './verifier-test-fixtures.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {sha256} from './contract.mjs';
test('browser runner refuses local execution without touching output or launching Chromium',()=>{
 const file=new URL('./browser-runner.mjs',import.meta.url);assert.ok(fs.existsSync(file),'M975 exact-CI browser runner required');
 const out=path.join(os.tmpdir(),'m975-refusal-'+process.pid),env={...process.env};delete env.GITHUB_ACTIONS;const result=spawnSync(process.execPath,[file.pathname,'missing-runtime',out],{env,encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/authorized exact-commit GitHub CI/);assert.equal(fs.existsSync(out),false);
});
test('native runtime identity rejects changed binary, wrong COMMIT and missing SHA inventory',async()=>{
 const m=await import('./browser-runner.mjs').catch(()=>null);assert.ok(m,'M975 exact-CI browser runner required');const root=fs.mkdtempSync(path.join(os.tmpdir(),'m975-native-pin-')),commit='a'.repeat(40),name='m975_model_exchange_probe';
 try{fs.writeFileSync(path.join(root,name),'fixture-native-binary');fs.writeFileSync(path.join(root,'COMMIT'),commit+'\n');fs.writeFileSync(path.join(root,'QT_VERSION'),'6.8.3\n');const hash=sha256('fixture-native-binary');fs.writeFileSync(path.join(root,'SHA256SUMS'),hash+'  '+name+'\n');assert.equal(m.verifyNativeRuntime(root,commit).sha256,hash);fs.appendFileSync(path.join(root,name),'changed');assert.throws(()=>m.verifyNativeRuntime(root,commit));fs.writeFileSync(path.join(root,name),'fixture-native-binary');assert.throws(()=>m.verifyNativeRuntime(root,'b'.repeat(40)));fs.writeFileSync(path.join(root,'SHA256SUMS'),'');assert.throws(()=>m.verifyNativeRuntime(root,commit));}finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('raw delta rejection proves actual import-only refusal and source preservation',async()=>{
 const {verifyNativeResult}=await import('./browser-runner.mjs'),raw='{"format":"pandolab-autosave-delta"}',bytes=Buffer.from(raw),request={id:'delta-refusal',mode:'reject',inputSha256:sha256(bytes),expectedError:'BASE_DATA_REQUIRED',expectedStages:['rejected'],actions:[]},result={schema:'pando-m975-native-exchange-result',version:1,id:request.id,mode:'reject',runtime:{compiledQt:'6.8.3',qt:'6.8.3'},input:{base64:bytes.toString('base64'),size:bytes.length,sha256:sha256(bytes)},inputAfter:{base64:bytes.toString('base64'),size:bytes.length,sha256:sha256(bytes)},sourcePreserved:true,inputObservations:[],stageOrder:['rejected'],stages:{rejected:{observed:true,accepted:false,error:'BASE_DATA_REQUIRED',refusalPhase:'import',importOnly:true,publicationAttempted:false,projectOutputPublished:false,sourcePreserved:true,canonicalUnchanged:true,historyUnchanged:true}},actions:[]};
 assert.doesNotThrow(()=>verifyNativeResult(result,request,raw));for(const field of ['importOnly','sourcePreserved','canonicalUnchanged','historyUnchanged']){const r=structuredClone(result);r.stages.rejected[field]=false;assert.throws(()=>verifyNativeResult(r,request,raw));}for(const field of ['publicationAttempted','projectOutputPublished']){const r=structuredClone(result);r.stages.rejected[field]=true;assert.throws(()=>verifyNativeResult(r,request,raw));}const overstated=structuredClone(result);overstated.stages.rejected.sentinelUnchanged=true;assert.throws(()=>verifyNativeResult(overstated,request,raw));const r=structuredClone(result);r.stages.rejected.error='wrong';assert.throws(()=>verifyNativeResult(r,request,raw));const published=structuredClone(result);published.stages.rejected.webFile={raw:'published despite refusal'};assert.throws(()=>verifyNativeResult(published,request,raw));
});
test('native observed, actual Qt runtime and canonical QFile equality fail closed independently',async()=>{
 const {verifyNativeResult}=await import('./browser-runner.mjs'),envelope=raw=>({raw,base64:Buffer.from(raw).toString('base64'),size:Buffer.byteLength(raw),sha256:sha256(raw)}),raw='{"source":1}',request={id:'codec-proof',mode:'codec',inputSha256:sha256(raw),expectedStages:['storage'],actions:[]},document=envelope('{"canonical":1}'),result={schema:'pando-m975-native-exchange-result',version:1,id:request.id,mode:'codec',runtime:{compiledQt:'6.8.3',qt:'6.8.3'},input:envelope(raw),inputAfter:envelope(raw),sourcePreserved:true,inputObservations:[],stageOrder:['storage'],stages:{storage:{observed:true,document,nativeFile:{...document,reopenEqual:true,codecFileRoundtrip:true,saveMethod:'QFile-production-codec'},webFile:envelope('{"web":1}')}},actions:[]};
 assert.doesNotThrow(()=>verifyNativeResult(result,request,raw));for(const mutate of [r=>r.stages.storage.observed=false,r=>r.runtime.qt='0.0.0',r=>r.runtime.compiledQt='0.0.0',r=>Object.assign(r.stages.storage.nativeFile,envelope('{"OTHERFILE":99}'))]){const r=structuredClone(result);mutate(r);assert.throws(()=>verifyNativeResult(r,request,raw));}
});
test('inactive edits cannot substitute codec saves and active previews prove save refusal',async()=>{
 const {verifyNativeResult}=await import('./browser-runner.mjs'),{input:raw,request,result}=editVerifierFixture();
 assert.doesNotThrow(()=>verifyNativeResult(result,request,raw));for(const mutate of [r=>Object.assign(r.stages.before.nativeFile,{saveMethod:'QFile-production-codec',codecFileRoundtrip:true}),r=>r.stages.preview.nativeFile.destinationUnchanged=false,r=>r.stages.preview.nativeFile.saveAccepted=true,r=>Object.assign(r.stages.preview.nativeFile,{saveMethod:'EditorController.saveFile/openFile',saveAccepted:true})]){const r=structuredClone(result);mutate(r);assert.throws(()=>verifyNativeResult(r,request,raw));}
});
