import test from 'node:test';import assert from 'node:assert/strict';
import {verifyNativeResult} from './browser-runner.mjs';import {editVerifierFixture,testBlob} from './verifier-test-fixtures.mjs';
const valid=editVerifierFixture(),negative=editVerifierFixture({rejected:true});
test('complete action-derived native coordinate and stage evidence is valid',()=>assert.doesNotThrow(()=>verifyNativeResult(valid.result,valid.request,valid.input)));
for(const [name,mutate]of [
 ['missing coordinate observations',r=>delete r.inputObservations],['empty coordinate inventory',r=>r.inputObservations=[]],['extra coordinate observation',r=>r.inputObservations.push(structuredClone(r.inputObservations[0]))],['reordered intended points',r=>r.inputObservations.reverse()],['wrong coordinate action',r=>r.inputObservations[0].op='move-node'],['wrong intended coordinate',r=>r.inputObservations[0].intended=[999,999]],['wrong inverse',r=>r.inputObservations[0].inverse=[999,999]],['non-exact preimage',r=>r.inputObservations[0].exact=false],['expanded ULP bound',r=>r.inputObservations[0].maximumUlpRadius=100],['out-of-bound ULP step',r=>r.inputObservations[0].xUlpSteps=100],['fractional ULP step',r=>r.inputObservations[0].yUlpSteps=0.5],['chosen point not accounted by ULP steps',r=>r.inputObservations[0].chosen[0]+=0.1],['missing input view',r=>delete r.inputObservations[0].view],['missing actual input projection',r=>delete r.inputObservations[0].controllerProjection],['changed actual input projection',r=>r.inputObservations[0].controllerProjection.cosLatitude=0.8],['missing preview state',r=>delete r.stages.preview.state],['missing preview view',r=>delete r.stages.preview.mapViewState],['wrong supplied initial view',r=>r.stages.before.mapViewState.scale=200],['contradictory precommit view',r=>r.stages.preview.mapViewState.scale+=1],['contradictory precommit projection',r=>r.stages.cancel.controllerProjection.minX+=1],['wrong preview activity',r=>r.stages.preview.state.active=false],['preview never ready',r=>r.stages.preview.state.previewReady=false],['preview still calculating',r=>r.stages.preview.state.calculating=true],['persistence altered canonical',r=>r.stages.preview.nativeFile.canonicalUnchanged=false],['persistence altered history',r=>r.stages.preview.nativeFile.historyUnchanged=false],['stage acceptance differs from public action',r=>r.stages.preview.accepted=false],['source preservation false',r=>r.sourcePreserved=false],['source reread missing',r=>delete r.inputAfter],['source reread changed',r=>r.inputAfter=testBlob('{"changed":1}')],
])test('rejects '+name,()=>{const r=structuredClone(valid.result);mutate(r);assert.throws(()=>verifyNativeResult(r,valid.request,valid.input));});
test('rejects wrong current commit failure while preserving nominal hash/history/stages',()=>{
 assert.doesNotThrow(()=>verifyNativeResult(negative.result,negative.request,negative.input));
 for(const mutate of [r=>r.stages.rejected.errors=[],r=>{r.actions.at(-1).errors=r.stages.rejected.errors=['UNKNOWN_TOOL: unrelated failure'];},r=>{r.actions.at(-1).errors=r.stages.rejected.errors=['GEOMETRY_EDIT_ACTIVE: refusal after save'];},r=>r.stages.rejected.accepted=true,r=>r.stages.rejected.state.error='UNKNOWN_TOOL',r=>r.actions.at(-1).errors=[]]){const r=structuredClone(negative.result);mutate(r);assert.throws(()=>verifyNativeResult(r,negative.request,negative.input));}
});
