import test from 'node:test';import assert from 'node:assert/strict';import {sha256} from './contract.mjs';
const modulePromise=import('./ownership-accounting.mjs').catch(()=>null);
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort((a,b)=>Buffer.compare(Buffer.from(a),Buffer.from(b))).map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
const labelId='97500000-0000-4000-8000-000000000002',derivedId='web-label:'+labelId,labelSlot='/labels/'+labelId+'/source/details';
const ref=(id,version=1)=>({id,version}),row=(id,x,version=1)=>({id,version,geojson:{type:'Point',coordinates:[x,2]}}),derived=()=>({ref:ref(derivedId),createdFor:{domain:'label',id:labelId},geometrySha256:sha256(canonical(row(derivedId,3).geojson)),promoted:false});
function fixture({fate='live',promoted=false,uncertain=false}={}){
 const sourceRow=row('source-shape',1),inline=row(derivedId,3),allocation={...derived(),promoted},before={format:'pandoeditor-project',version:10,documentId:'native-original',units:[],timelineRecords:{schemaVersion:1,lifetimes:[],geometryBindings:[],parentRelations:[]},geometries:[sourceRow,inline],content:{labels:[{id:labelId,geometryRef:allocation.ref,source:{details:{note:[1,'x']}}}],hydro:[],genericFeatures:[],distributionLayers:[],distributionEntries:[],countryDetails:[],symbols:[],physicalData:{dataset:'',version:'',source:'',hiddenHydroIds:[]}},presentation:{keep:['second','first']},extensions:[],exchangeMetadata:{source:'unchanged'},geometryProvenance:{schemaVersion:1,originalArchive:[ref('source-shape')],inlineAllocations:[allocation],opaqueBaseline:[{path:'/exchangeMetadata',sha256:sha256(canonical({source:'unchanged'}))},{path:labelSlot,sha256:sha256(canonical({note:[1,'x']}))}],opaqueUncertain:uncertain}};
 const initial=structuredClone(before);if(fate==='deleted')before.content.labels=[];if(fate==='detached'){before.geometries.push(row('native-shape',4));before.content.labels[0].geometryRef=ref('native-shape');}
 const after=structuredClone(before);after.documentId='native-reimport';const live=fate==='live';if(!promoted&&!live)after.geometries=after.geometries.filter(g=>g.id!==derivedId);after.geometryProvenance.originalArchive=after.geometries.filter(g=>promoted||g.id!==derivedId).map(g=>ref(g.id,g.version));after.geometryProvenance.inlineAllocations=!promoted&&live?[derived()]:[];after.geometryProvenance.opaqueUncertain=false;if(fate==='deleted')after.geometryProvenance.opaqueBaseline=after.geometryProvenance.opaqueBaseline.filter(r=>!r.path.startsWith('/labels/'));
 const source={format:'pandolab-project-state',schemaVersion:9,source:'unchanged',geometries:[sourceRow]},web={format:'pandolab-project-state',schemaVersion:9,source:'unchanged',geometries:after.geometries.filter(g=>promoted||g.id!==derivedId),labels:after.content.labels.map(l=>({id:l.id,source:structuredClone(l.source),coordinates:after.geometries.find(g=>g.id===l.geometryRef.id&&g.version===l.geometryRef.version).geojson.coordinates})),hydroEdits:[],genericFeatures:[],distributionEntries:[]};
 return {before,after,initial,source,web,raw:()=>({nativeBeforeRaw:canonical(before)+'\n',nativeAfterRaw:canonical(after)+'\n',webOutputRaw:canonical(web),browserInputRaw:canonical(web),caseId:'unit-explicit-accounting',stage:'confirm'})};
}
test('accounts every retained semantic and exact regenerated live-derived row',async()=>{const m=await modulePromise;assert.ok(m,'explicit native-v10 ownership accounting required');const f=fixture(),receipt=m.accountNativeRoundTrip(f.raw());assert.deepEqual(receipt.rows.map(r=>r.fate),['semantic-retained','live-regenerated']);assert.equal(receipt.rows[1].geometrySha256,derived().geometrySha256);assert.equal(receipt.rows[1].users.length,1);});
for(const fate of ['deleted','detached'])test('explicitly accounts omitted creator '+fate+' with zero users',async()=>{const m=await modulePromise;assert.ok(m);const f=fixture({fate}),receipt=m.accountNativeRoundTrip(f.raw()),r=receipt.rows.find(r=>r.ref.id===derivedId);assert.equal(r.fate,fate==='deleted'?'owner-deleted':'creator-detached-rebound');assert.deepEqual(r.users,[]);assert.equal(r.creator.exists,fate!=='deleted');});
test('promoted rows become original semantic; uncertain reset allowed only with no omissions',async()=>{const m=await modulePromise;assert.ok(m);const f=fixture({promoted:true,uncertain:true}),r=m.accountNativeRoundTrip(f.raw());assert.equal(r.rows.find(r=>r.ref.id===derivedId).reason,'promoted-inline');assert.deepEqual(r.opaqueUncertainty,{before:true,after:false,reason:'fresh-import-no-derived-omissions'});});
test('every extra/missing/changed row and forged ownership claim fails closed',async()=>{const m=await modulePromise;assert.ok(m);for(const mutate of [
 f=>f.after.geometries.push(row('unaccounted',9)),f=>f.after.geometries.splice(0,1),f=>f.after.geometries[0].geojson.coordinates[0]+=1e-15,f=>f.after.geometryProvenance.originalArchive=[],f=>f.after.geometryProvenance.inlineAllocations[0].promoted=true,f=>f.before.geometryProvenance.inlineAllocations[0].geometrySha256='0'.repeat(64),f=>f.before.geometryProvenance.inlineAllocations[0].createdFor.id='other',f=>f.before.geometryProvenance.inlineAllocations.push(derived()),f=>f.before.geometryProvenance.originalArchive.push(ref(derivedId)),f=>f.before.geometryProvenance.opaqueUncertain=true,f=>f.after.content.labels[0].geometryRef=ref('source-shape'),f=>f.web.geometries.push(row(derivedId,3)),f=>f.after.geometryProvenance.opaqueBaseline.push({path:'/unknown/forged',sha256:'0'.repeat(64)}),f=>f.after.presentation.keep.reverse(),
 ]){const f=fixture();mutate(f);assert.throws(()=>m.accountNativeRoundTrip(f.raw()));}});
test('opaque slot removal has current-owner proof and opaque changes cannot be ignored',async()=>{const m=await modulePromise;assert.ok(m);const deleted=fixture({fate:'deleted'}),receipt=m.accountNativeRoundTrip(deleted.raw());assert.equal(receipt.opaqueSlots.find(r=>r.path===labelSlot).reason,'owner-deleted');for(const mutate of [f=>f.after.content.labels[0].source.details.note.reverse(),f=>f.before.geometryProvenance.opaqueBaseline[1].sha256='f'.repeat(64),f=>f.after.geometryProvenance.opaqueBaseline.pop()]){const f=fixture();mutate(f);assert.throws(()=>m.accountNativeRoundTrip(f.raw()));}});
test('unreferenced semantic native rows remain valid and must be retained',async()=>{const m=await modulePromise;assert.ok(m);const f=fixture();f.before.geometries.push(row('unreferenced-native',7));f.after.geometries.push(row('unreferenced-native',7));f.after.geometryProvenance.originalArchive.push(ref('unreferenced-native'));f.web.geometries.push(row('unreferenced-native',7));const r=m.accountNativeRoundTrip(f.raw());assert.equal(r.rows.find(r=>r.ref.id==='unreferenced-native').reason,'native-semantic');f.after.geometries.pop();assert.throws(()=>m.accountNativeRoundTrip(f.raw()));});
test('lossless fingerprinting preserves actual numeric and string source tokens',async()=>{const m=await modulePromise;assert.ok(m);assert.equal(m.losslessCanonical('{"z":9007199254740993,"a":"\\u0061"}'),'{"a":"\\u0061","z":9007199254740993}');assert.notEqual(m.losslessCanonical('{"n":9007199254740993}'),m.losslessCanonical('{"n":9007199254740992}'));assert.throws(()=>m.losslessCanonical('{"n":1,"n":2}'));});
function sourceFor(f){return canonical({...f.source,labels:[{id:labelId,coordinates:[3,2],source:structuredClone(f.initial.content.labels[0].source)}],hydroEdits:[],genericFeatures:[],distributionEntries:[]});}
function corpusContext(f){return {sourceWebRaw:sourceFor(f),initialNativeRaw:canonical(f.initial)+'\n',operation:'split',declaredCorpus:true,history:[{stage:'confirm',nativeRaw:canonical(f.before)+'\n',actions:[{op:'confirm',accepted:true}]}]};}
test('fresh web import accounts only source originals and genuine live inline allocations',async()=>{const m=await modulePromise;assert.ok(m);assert.equal(typeof m.accountWebNativeExchange,'function');const f=fixture(),r=m.accountWebNativeExchange({sourceWebRaw:sourceFor(f),nativeRaw:canonical(f.before)+'\n',webOutputRaw:canonical(f.web),browserInputRaw:canonical(f.web)});assert.equal(r.rows.find(r=>r.ref.id===derivedId).fate,'live-inline-preserved');const extra=structuredClone(f.before);extra.geometries.push(row('extra-native',9));assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw:sourceFor(f),nativeRaw:canonical(extra)+'\n',webOutputRaw:canonical(f.web),browserInputRaw:canonical(f.web)}));});
test('declared corpus rejects self-consistent extra rows and invented historical baselines',async()=>{const m=await modulePromise;assert.ok(m);for(const mutate of [f=>{const extra=row('unaccounted-extra',9);f.before.geometries.push(extra);f.after.geometries.push(extra);f.after.geometryProvenance.originalArchive.push(ref(extra.id));f.web.geometries.push(extra);},f=>{f.before.geometryProvenance.opaqueBaseline.push({path:'/labels/missing/source/details',sha256:'f'.repeat(64)});}]){const f=fixture();mutate(f);assert.throws(()=>m.accountNativeRoundTrip({...f.raw(),context:corpusContext(f)}));}});
test('declared corpus records exact command checkpoint proof for new native semantic row',async()=>{const m=await modulePromise;const f=annexFixture(),r=m.accountNativeRoundTrip({...f.raw(),context:f.context()}),added=r.rows.find(row=>row.ref.id==='native-target');assert.equal(added.creationEvidence.stage,'confirm');assert.equal(added.creationEvidence.reason,'typed-native-command-version');assert.match(added.creationEvidence.nativeSha256,/^[a-f0-9]{64}$/);});
test('a forged promotion cannot hide behind a consistent emitted archive',async()=>{const m=await modulePromise;assert.ok(m);const f=fixture({promoted:true});f.initial.geometryProvenance.inlineAllocations[0].promoted=false;assert.throws(()=>m.accountNativeRoundTrip({...f.raw(),context:corpusContext(f)}));});

for(const suffix of ['\n','\r\n'])test('allocation creator UUID rejects trailing '+JSON.stringify(suffix),async()=>{const m=await modulePromise;const f=fixture(),bad=labelId+suffix;for(const document of [f.before,f.after]){document.content.labels[0].id=bad;document.content.labels[0].source.details={};document.content.labels[0].geometryRef.id='web-label:'+bad;document.geometries.find(r=>r.id===derivedId).id='web-label:'+bad;const a=document.geometryProvenance.inlineAllocations[0];a.createdFor.id=bad;a.ref.id='web-label:'+bad;document.geometryProvenance.opaqueBaseline=document.geometryProvenance.opaqueBaseline.filter(r=>!r.path.startsWith('/labels/'));}assert.throws(()=>m.accountNativeRoundTrip(f.raw()));});

test('web inline owner loss or wrong emitted shape cannot be hidden by a correct archive',async()=>{const m=await modulePromise;for(const mutate of [f=>f.web.labels=[],f=>f.web.labels[0].coordinates=[88,89]]){const f=fixture();mutate(f);assert.throws(()=>m.accountNativeRoundTrip(f.raw()));}});

test('metadata-only accepted confirm cannot authorize declared-corpus native geometry insertion',async()=>{const m=await modulePromise,f=fixture({fate:'detached'}),context={...corpusContext(f),operation:'metadata'};assert.throws(()=>m.accountNativeRoundTrip({...f.raw(),context}));});
test('fresh import follows deterministic-original and first-matching-original reference precedence',async()=>{const m=await modulePromise;const matching=fixture();for(const d of [matching.before,matching.after,matching.initial,matching.source,matching.web])d.geometries[0].geojson.coordinates=[3,2];assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw:sourceFor(matching),nativeRaw:canonical(matching.before),webOutputRaw:canonical(matching.web)}));const f=fixture();f.source.geometries.push(row(derivedId,3));f.before.geometryProvenance.originalArchive.push(ref(derivedId));f.before.geometryProvenance.inlineAllocations=[];f.before.content.labels[0].geometryRef=ref('source-shape');f.before.geometries[0].geojson.coordinates=[3,2];f.source.geometries[0].geojson.coordinates=[3,2];f.web.geometries.push(row(derivedId,3));f.web.geometries[0].geojson.coordinates=[3,2];assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw:sourceFor(f),nativeRaw:canonical(f.before),webOutputRaw:canonical(f.web)}));});
test('opaque source/native/web/browser boundaries preserve unsafe numeric tokens exactly',async()=>{const m=await modulePromise,f=fixture();for(const d of [f.before,f.initial]){d.content.labels[0].source.details.reviewUnsafe=9007199254740992;d.geometryProvenance.opaqueBaseline.find(r=>r.path===labelSlot).sha256=sha256(canonical(d.content.labels[0].source.details));}f.web.labels[0].source.details.reviewUnsafe=9007199254740992;const nativeRaw=canonical(f.before),webRaw=canonical(f.web),source=sourceFor(f),changed=s=>s.replace('\"reviewUnsafe\":9007199254740992','\"reviewUnsafe\":9007199254740993');assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw:changed(source),nativeRaw,webOutputRaw:webRaw}));assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw:source,nativeRaw,webOutputRaw:webRaw,browserInputRaw:changed(webRaw)}));});

function annexFixture(){
 const f=fixture(),ids=['target','donor','independent-region'];
 for(const doc of [f.initial,f.before,f.after]){doc.units=ids.map(id=>({id,metadata:{}}));doc.timelineRecords.geometryBindings=ids.map(id=>({id:'binding:'+id,entityId:id,geometryRef:ref('shape:'+id)}));doc.timelineRecords.parentRelations=ids.map(id=>({entityId:id,parentId:''}));for(const [i,id]of ids.entries()){doc.geometries.push(row('shape:'+id,10+i));doc.geometryProvenance.originalArchive.push(ref('shape:'+id));}}
 for(const id of ['target','donor'])for(const doc of [f.before,f.after]){doc.geometries.push(row('native-'+id,20+ids.indexOf(id)));doc.timelineRecords.geometryBindings.find(b=>b.entityId===id).geometryRef=ref('native-'+id);if(doc===f.after)doc.geometryProvenance.originalArchive.push(ref('native-'+id));}
 const webFor=doc=>({...f.web,geometries:doc.geometries.filter(g=>g.id!==derivedId),territorialEntities:ids.map(id=>({id,properties:{metadata:{}}})),timelineRecords:structuredClone(doc.timelineRecords),labelSettings:{},layerPresentation:{objectStyles:{}}});
 Object.assign(f.web,webFor(f.before));const initialWeb=webFor(f.initial);f.context=()=>({sourceWebRaw:canonical(initialWeb),initialWebRaw:canonical(initialWeb),initialNativeRaw:canonical(f.initial),operation:'annex',definition:{operation:'annex',full:false},declaredCorpus:true,history:[{stage:'confirm',nativeRaw:canonical(f.before),webRaw:canonical(f.web),actions:[{op:'begin',tool:'annex',accepted:true},{op:'confirm',accepted:true}]}]});return f;
}
test('geometry command does not authorize unrelated or same-shape native version insertion',async()=>{const m=await modulePromise;for(const owner of ['independent-region','target']){const f=annexFixture();m.accountNativeRoundTrip({...f.raw(),context:f.context()});const original=f.initial.geometries.find(g=>g.id==='shape:'+owner),extra={...structuredClone(original),id:'forged-unrelated'};for(const doc of [f.before,f.after,f.web]){doc.geometries.push(extra);doc.timelineRecords.geometryBindings.find(b=>b.entityId===owner).geometryRef=ref(extra.id);}f.after.geometryProvenance.originalArchive.push(ref(extra.id));assert.throws(()=>m.accountNativeRoundTrip({...f.raw(),context:f.context()}));}});
test('native creation evidence binds the accepted tool and real geometry effect',async()=>{const m=await modulePromise;for(const mutate of [c=>c.history[0].actions[0].tool='metadata',c=>c.definition.operation='delete',c=>delete c.history[0].webRaw]){const f=annexFixture(),context=f.context();m.accountNativeRoundTrip({...f.raw(),context});mutate(context);assert.throws(()=>m.accountNativeRoundTrip({...f.raw(),context}));}});

test('equal-original selection uses numeric version order rather than source array or lexical ref order',async()=>{const m=await modulePromise,f=fixture();f.before.geometries=f.before.geometries.filter(g=>g.id!==derivedId);f.before.geometryProvenance.inlineAllocations=[];for(const version of [10,2]){const g=row('shared-original',3,version);for(const d of [f.before,f.source,f.web])d.geometries.push(structuredClone(g));f.before.geometryProvenance.originalArchive.push(ref(g.id,version));}f.before.content.labels[0].geometryRef=ref('shared-original',2);const check=()=>m.accountWebNativeExchange({sourceWebRaw:sourceFor(f),nativeRaw:canonical(f.before),webOutputRaw:canonical(f.web)});check();f.before.content.labels[0].geometryRef.version=10;assert.throws(check);});
test('opaque web string escapes and nested array order remain exact across export and resave',async()=>{const m=await modulePromise,f=fixture(),nativeRaw=canonical(f.before),sourceWebRaw=sourceFor(f),webOutputRaw=canonical(f.web);m.accountWebNativeExchange({sourceWebRaw,nativeRaw,webOutputRaw});const escaped=webOutputRaw.replace('"x"','"\\u0078"');assert.notEqual(escaped,webOutputRaw);assert.deepEqual(JSON.parse(escaped),JSON.parse(webOutputRaw));assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw,nativeRaw,webOutputRaw,browserInputRaw:escaped}));f.web.labels[0].source.details.note.reverse();assert.throws(()=>m.accountWebNativeExchange({sourceWebRaw,nativeRaw,webOutputRaw:canonical(f.web)}));});
