import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {loadExchangeSources} from './sources.mjs';
import {verifyRawRecord,rawRecord} from './contract.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../../tests/fixtures/web-m975-model-exchange/manifest.json',import.meta.url)));
test('actual production reader, edits, serializer and history observe every exact fixture stage (Node diagnostic only)',async()=>{
 const runtime=await import('./runtime.mjs').catch(()=>null);assert.ok(runtime,'M975 exchange runtime must exist');
 const loaded=await loadExchangeSources();const {createExchangeSuite,exchangeRuntimeSource,verifyBrowserRows}=await import('./suite.mjs');const browserRuntime=(0,eval)(exchangeRuntimeSource());const rows=[];
 try{for(const definition of manifest.cases){const raw=fs.readFileSync(new URL('../../tests/fixtures/web-m975-model-exchange/'+definition.file,import.meta.url),'utf8');const row=await browserRuntime.runExchangeCase({...loaded,runtime:browserRuntime,selectionRuntime:browserRuntime.selectionRuntime},{...definition,inputRaw:raw});rows.push(row);assert.equal(row.case,definition.id);assert.deepEqual(Object.keys(row.stages),definition.stages);for(const stage of Object.values(row.stages)){const p=JSON.parse(verifyRawRecord(stage.save));loaded.api.prepareProjectForStorage(p);assert.ok(stage.reader.storage);}
  if(definition.operation!=='storage'){assert.equal(row.stages.before.history.undo,0);assert.equal(row.stages.before.inputInstalled,true);if(definition.reject)assert.deepEqual(JSON.parse(row.stages.rejected.save.raw),JSON.parse(row.stages.before.save.raw));else{assert.equal(row.stages.confirm.history.undo,1);assert.equal(row.stages.undo.history.redo,1);assert.equal(row.stages.redo.history.undo,1);}}
  if(definition.id==='m975-annex-full-recursive'){assert.ok(row.controls.delta.changedIds.length);assert.ok(row.controls.delta.removedIds.length);assert.equal(row.controls.delta.missingBaselineRejected,true);assert.equal(row.controls.delta.wrongBaselineRejected,true);assert.equal(Object.hasOwn(JSON.parse(row.controls.delta.recoveredStorage.raw),'physicalSourceInfo'),false);assert.deepEqual(JSON.parse(row.controls.delta.recovered.raw),JSON.parse(row.stages.redo.save.raw));}
 }const suite=createExchangeSuite({commit:'a'.repeat(40),runId:'node-diagnostic',native:{commit:'a'.repeat(40),sha256:'b'.repeat(64)}});verifyBrowserRows(suite,rows);for(const stage of ['before','confirm','undo','redo']){const changed=structuredClone(rows),row=changed[0],p=JSON.parse(row.stages[stage].save.raw);p.territorialEntities[0].properties.name+=' mutation';row.stages[stage].save=rawRecord(JSON.stringify(p));assert.throws(()=>verifyBrowserRows(suite,changed),stage+' semantic mutation rejected');}const missingArchive=structuredClone(rows),rich=missingArchive.at(-1),lost=JSON.parse(rich.stages.storage.save.raw);lost.geometries.pop();rich.stages.storage.save=rawRecord(JSON.stringify(lost));assert.throws(()=>verifyBrowserRows(suite,missingArchive),'rich storage retains every source archive field');const noOp=structuredClone(rows);noOp[0].stages.confirm.save=structuredClone(noOp[0].stages.before.save);assert.throws(()=>verifyBrowserRows(suite,noOp));for(const operation of ['annex','split','boundary','delete']){const changed=structuredClone(rows),index=suite.cases.findIndex(c=>c.operation===operation&&!c.reject),row=changed[index],fake=JSON.parse(row.stages.before.save.raw);fake.sourceInfo={...fake.sourceInfo,reviewCounter:'fake edit'};row.stages.confirm.save=rawRecord(JSON.stringify(fake));row.stages.redo.save=rawRecord(JSON.stringify(fake));assert.throws(()=>verifyBrowserRows(suite,changed),operation+' arbitrary metadata change cannot fake an edit');}}finally{loaded.cleanup();}
});
