import assert from 'node:assert/strict';import {gunzipSync} from 'node:zlib';import fs from 'node:fs';import path from 'node:path';
import {readExchangeSources,exchangeEntrypoints} from './sources.mjs';
import {lifecycleRuntimeSource} from '../m974-snap-boundary/sources.mjs';
import {createSelectionRuntime,selectionCutView,seedSelectionFeatures,square,observeSelection} from '../m97/web-selection.mjs';
import {createSplitRuntime,settleSplit,seedSplitFeatures} from '../m97/web-split.mjs';
import {runBoundaryCase,extractBoundaryCallbacks} from '../m974-snap-boundary/boundary-runtime.mjs';
import * as exchange from './runtime.mjs';
import {sha256,verifyRawRecord,verifyInventory,assertExchangeEqual} from './contract.mjs';
import {runtimePin} from '../m97/river/suite.mjs';
export {runtimePin};
const fixtureRoot=new URL('../../tests/fixtures/web-m975-model-exchange/',import.meta.url);
export const observationLimits=Object.freeze({actualProductionSerializer:true,actualProductionReaders:true,actualEditServices:true,actualWorker:true,fullSavedDocuments:true,eachEngineCheckpointExchange:true,crossEngineEditGeometryParity:false,fullDOM:false,filePickerUI:false,pixelProjection:false,gpu:false,historyStacksSerialized:false,nodeAuthoritative:false});
export const inputManifestPin='c0211b9af824c1a84d9a6b691eaa92802bb7bcbb42a222b6e0633afe9368f031';
export function readInputs(){const manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',fixtureRoot)));assert.equal(sha256(JSON.stringify(manifest)),inputManifestPin,'immutable new valid-v9 input manifest');assert.equal(manifest.schema,'pando-m975-model-exchange-inputs');assert.equal(manifest.version,2);const prior=manifest.previousInputs,priorCompressed=fs.readFileSync(new URL(prior.file,fixtureRoot));assert.equal(priorCompressed.length,prior.bytes);assert.equal(sha256(priorCompressed),prior.sha256,'retained v1 input bytes');const priorRaw=gunzipSync(priorCompressed);assert.equal(priorRaw.length,prior.decompressedBytes);assert.equal(sha256(priorRaw),prior.decompressedSha256);assert.equal(sha256(fs.readFileSync(new URL(manifest.coordinateRevision.failureFile,fixtureRoot))),manifest.coordinateRevision.failureSha256,'retained v1 exact-preimage failures');const cases=manifest.cases.map(row=>{const inputRaw=fs.readFileSync(new URL(row.file,fixtureRoot),'utf8');assert.equal(Buffer.byteLength(inputRaw),row.bytes);assert.equal(sha256(inputRaw),row.sha256);return {...row,inputRaw};});assert.equal(new Set(cases.map(c=>c.id)).size,cases.length);return {manifest,cases};}
export function exchangeRuntimeSource(){
 const helpers=[selectionCutView,seedSelectionFeatures,createSelectionRuntime,observeSelection,seedSplitFeatures,createSplitRuntime,settleSplit,extractBoundaryCallbacks,runBoundaryCase,...Object.values(exchange)];
 return `(()=>{const clone=value=>structuredClone(value),noop=()=>{},square=${square.toString()},assert={ok:(v,m)=>{if(!v)throw Error(m||'Assertion failed');},equal:(a,b,m)=>{if(a!==b)throw Error(m||'Equality failed');},deepEqual:(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(m||'Exact input equality failed');}};const lifecycle=${lifecycleRuntimeSource()};const {createRuntime,observe,referenceEffects}=lifecycle;${helpers.map(fn=>'const '+fn.name+'='+fn.toString()+';').join('\n')}return {...lifecycle,runExchangeCase,reopenExchange,selectionRuntime:{createSelectionRuntime,selectionCutView,seedSelectionFeatures,square}};})()`;
}
const harnessFiles=()=>Object.fromEntries(['contract.mjs','native-contract.mjs','sources.mjs','runtime.mjs','suite.mjs','browser-runner.mjs','../m97/web-lifecycle.mjs','../m97/web-selection.mjs','../m97/web-split.mjs','../m974-snap-boundary/boundary-runtime.mjs','../m974-snap-boundary/sources.mjs','../m974-snap-boundary/source-history-sources.mjs','../m974-snap-boundary/worker-host.mjs','../m97/river/browser/report-transfer.mjs'].map(name=>[name,sha256(fs.readFileSync(new URL(name,import.meta.url)))]));
const identity=s=>({schema:s.schema,version:s.version,commit:s.commit,runId:s.runId,native:structuredClone(s.native),runtimePin:s.runtimePin,sourceManifestSha256:sha256(JSON.stringify(s.manifest)),sourceSupplementSha256:sha256(JSON.stringify(s.supplement)),sourcesSha256:sha256(JSON.stringify(s.sources)),evidenceSourcesSha256:sha256(JSON.stringify(s.evidenceSources)),inputManifestSha256:sha256(JSON.stringify(s.inputManifest)),casesSha256:sha256(JSON.stringify(s.cases)),runtimeSha256:s.runtime.sha256,harnessFiles:s.harnessFiles,caseStages:s.cases.map(c=>({id:c.id,stages:c.stages})),observationLimits});
export function createExchangeSuite({commit,runId,native}){assert.match(commit||'',/^[a-f0-9]{40}$/);assert.ok(runId);assert.equal(native.commit,commit);assert.match(native.sha256,/^[a-f0-9]{64}$/);const source=readExchangeSources(),input=readInputs(),runtime=exchangeRuntimeSource();const s={schema:'pando-m975-model-exchange-suite',version:1,commit,runId,native,runtimePin,...source,entrypoints:exchangeEntrypoints,inputManifest:input.manifest,cases:input.cases,runtime:{source:runtime,sha256:sha256(runtime)},harnessFiles:harnessFiles()};s.identity=identity(s);return s;}
export function verifyExchangeSuite(s){const expected=createExchangeSuite({commit:s.commit,runId:s.runId,native:s.native});assert.deepEqual(s,expected,'exact M975 source/input/harness/runtime/native binding');return s;}
export const browserExchangeStages=definition=>[...definition.stages,...(definition.id==='m975-annex-full-recursive'?['full-autosave','delta-recovered']:[])];
export function nativeRequest(definition,{codec=false,id=definition.id,sha=definition.sha256}={}){
 const base={schema:'pando-m975-native-exchange-request',version:1,id,mode:codec?'codec':definition.operation==='storage'?'timeline':'edit',format:'web',inputSha256:sha,...(definition.reject&&!codec?{expectedCommitError:'DANGLING_REF'}:{}),view:definition.definition?.view||selectionCutView(),expectedStages:codec?['storage']:definition.operation==='storage'?['storage','activation-rejected']:definition.stages,actions:[]};
 if(codec||definition.operation==='storage')return base;
 const sequence=[];const add=(op,extra={})=>sequence.push({op,...extra});add('observe',{stage:'before'});
 if(definition.operation==='delete'){add('select',{domain:'generic',id:definition.deleteId});add('begin',{tool:'delete'});add('confirm',{stage:'confirm'});add('undo',{stage:'undo'});add('redo',{stage:'redo'});return {...base,actions:sequence};}
 const begin=()=>{
  if(definition.operation==='boundary'){definition.definition.selectedIds.forEach((id,index)=>add('select',{id,additive:index>0}));add('begin',{tool:'shared-boundary'});add('move-node',definition.definition.move);return;}
  add('select',{id:definition.operation==='annex'?'target':'source'});add('begin',{tool:definition.operation});if(definition.operation==='annex')add('provider',{id:'donor'});add('advance');add('method',{method:definition.operation==='split'?'line':definition.full?'components':'polygon'});
  if(definition.operation==='annex'&&definition.full)add('component',{all:true});else{add('draft',{points:definition.operation==='split'?definition.definition.coords:[[-1,0],[4,0],[4,10],[-1,10]]});add('finish');if(definition.operation==='split'&&definition.definition.select!=='default')add('candidate',{indices:definition.definition.select});}
  if(!(definition.operation==='annex'&&definition.full))add('archive');add('advance');
 };
 begin();sequence.at(-1).stage='preview';add('cancel',{stage:'cancel'});begin();add('confirm',{stage:definition.reject?'rejected':'confirm',...(definition.reject?{expectAccepted:false}:{})});if(!definition.reject){add('undo',{stage:'undo'});add('redo',{stage:'redo'});}
 return {...base,...(definition.definition?.view?{view:definition.definition.view}:{}),actions:sequence};
}
export function verifyEditEffect(definition,before,after){
 const ids=p=>p.territorialEntities.map(f=>f.id),beforeIds=ids(before),afterIds=ids(after),binding=(p,id)=>p.timelineRecords.geometryBindings.find(r=>r.entityId===id),parent=(p,id)=>p.timelineRecords.parentRelations.find(r=>r.entityId===id)?.parentId;
 const geometry=(p,id)=>{const ref=binding(p,id)?.geometryRef;assert.ok(ref,'geometry binding '+id);const entry=p.geometries.find(g=>g.id===ref.id&&g.version===ref.version);assert.ok(entry,'bound immutable archive version '+id);return entry.geojson;};
 const changed=id=>{assert.notDeepEqual(binding(after,id).geometryRef,binding(before,id).geometryRef,'new geometry version for '+id);assert.notDeepEqual(geometry(after,id),geometry(before,id),'intended actual shape changed '+id);};
 for(const key of ['sourceInfo','labels','hydroEdits','distributionLayers','distributionEntries'])assert.deepEqual(after[key],before[key],'unrelated content preserved '+key);
 if(definition.operation==='delete'){
  assert.deepEqual(after.genericFeatures,before.genericFeatures.filter(f=>f.id!==definition.deleteId),'exact requested generic deletion and survivor order');assert.ok(before.genericFeatures.some(f=>f.id===definition.deleteId));assert.deepEqual(after.territorialEntities,before.territorialEntities);assert.deepEqual(after.timelineRecords,before.timelineRecords);assert.deepEqual(after.geometries,before.geometries);return;
 }
 assert.deepEqual(after.genericFeatures,before.genericFeatures,'unrelated fallback content preserved');
 for(const entry of before.geometries)assert.deepEqual(after.geometries.find(g=>g.id===entry.id&&g.version===entry.version),entry,'retained original immutable geometry archive');
 if(definition.operation==='annex'){
  changed('target');if(definition.full){assert.deepEqual(afterIds,beforeIds.filter(id=>!['donor','child-left','child-right'].includes(id)),'exact recursive donor removal');}else{assert.deepEqual(afterIds,beforeIds,'partial donor and child identities retained');changed('donor');}
 }else if(definition.operation==='split'){
  const created=afterIds.filter(id=>!beforeIds.includes(id));assert.equal(created.length,1,'exact one new split sibling');assert.deepEqual(afterIds.filter(id=>id!==created[0]),beforeIds,'original split identity order retained');assert.equal(parent(after,created[0]),parent(before,'source'),'new sibling immediate parent');changed('source');assert.ok(geometry(after,created[0]));
 }else if(definition.operation==='boundary'){
  const expected=definition.definition.expected;assert.deepEqual(afterIds,beforeIds.filter(id=>!(expected.deletedIds||[]).includes(id)),'exact boundary descendant removals');for(const id of expected.movedOwnerIds)changed(id);for(const id of expected.reparentedIds||[])assert.notEqual(parent(after,id),parent(before,id),'whole descendant immediately reparented');for(const id of expected.clippedIds||[])changed(id);
  if(definition.id==='m975-boundary-child-fixed-parent'){assert.deepEqual(binding(after,'P'),binding(before,'P'),'fixed parent binding unchanged');assert.deepEqual(geometry(after,'P'),geometry(before,'P'),'fixed parent geometry unchanged');}
 }
 const deleted=beforeIds.filter(id=>!afterIds.includes(id));for(const id of deleted){assert.ok(!after.timelineRecords.lifetimes.some(r=>r.entityId===id));assert.ok(!after.timelineRecords.geometryBindings.some(r=>r.entityId===id));assert.ok(!after.timelineRecords.parentRelations.some(r=>r.entityId===id||r.parentId===id));assert.ok(!after.labels.some(r=>r.territorialUnitId===id));assert.ok(!after.distributionEntries.some(r=>r.territorialUnitId===id));assert.ok(!Object.hasOwn(after.labelSettings,'territorial:'+id),'deleted territorial label setting cleaned');assert.ok(!Object.hasOwn(after.layerPresentation.objectStyles,'territorial:entity:'+id),'deleted territorial style cleaned');}
}
export function verifyBrowserRows(suite,rows){
 verifyInventory(suite.cases,rows);for(const [i,row]of rows.entries()){
  assert.equal(verifyRawRecord(row.input),suite.cases[i].inputRaw);for(const [name,stage]of Object.entries(row.stages)){assert.equal(stage.observed,true,'actual observed browser stage');const saved=JSON.parse(verifyRawRecord(stage.save));assert.equal(saved.schemaVersion,9);assert.equal(saved.format,'pandolab-project-state');assert.equal(stage.reader.storage,true);if(suite.cases[i].operation==='storage')assert.equal(stage.reader.activationRejected,true);else{assert.equal(stage.reader.activation,true);assert.equal(stage.inputInstalled,true);assert.ok(Number.isInteger(stage.history.undo)&&stage.history.undo>=0);assert.ok(Number.isInteger(stage.history.redo)&&stage.history.redo>=0);}}
  if(suite.cases[i].operation==='storage')assertExchangeEqual(JSON.parse(row.input.raw),JSON.parse(row.stages.storage.save.raw),'rich storage retains full exact input');
  if(suite.cases[i].operation!=='storage'){
   assertExchangeEqual(JSON.parse(row.input.raw),JSON.parse(row.stages.before.save.raw),'exact valid input installed before all edits');assert.equal(row.stages.before.history.undo,0);assert.equal(row.stages.before.history.redo,0);
   if(row.stages.preview){assertExchangeEqual(JSON.parse(row.stages.before.save.raw),JSON.parse(row.stages.preview.save.raw),'canonical preview is uncommitted');assertExchangeEqual(JSON.parse(row.stages.before.save.raw),JSON.parse(row.stages.cancel.save.raw),'cancel leaves canonical content');}
   if(suite.cases[i].reject){assertExchangeEqual(JSON.parse(row.stages.before.save.raw),JSON.parse(row.stages.rejected.save.raw),'rejected commit atomic');assert.deepEqual(row.stages.rejected.history,row.stages.before.history);assert.ok(row.controls.rejection.errors.length);}else{verifyEditEffect(suite.cases[i],JSON.parse(row.stages.before.save.raw),JSON.parse(row.stages.confirm.save.raw));assert.notDeepEqual(JSON.parse(row.stages.confirm.save.raw),JSON.parse(row.stages.before.save.raw),'actual committed document changed');assert.equal(row.stages.confirm.history.undo,1);assert.equal(row.stages.undo.history.redo,1);assert.equal(row.stages.redo.history.undo,1);const documentKeys=['territorialEntities','sourceInfo','labels','genericFeatures','hydroEdits','timelineRecords','geometries','distributionLayers','distributionEntries'];const content=stage=>{const p=JSON.parse(row.stages[stage].save.raw);return Object.fromEntries(documentKeys.map(key=>[key,p[key]]));};assert.deepEqual(content('undo'),content('before'),'Undo exact document/history scope');assert.deepEqual(content('redo'),content('confirm'),'Redo exact document/history scope');}
  }
  if(['annex','split','boundary'].includes(suite.cases[i].operation)){const operations=row.trace.filter(t=>t.direction==='request'&&t.message.type==='execute').map(t=>t.message.operation);assert.ok(operations.length,'real Worker edit RPC observations');const required=suite.cases[i].operation==='split'?['territorial-cut']:suite.cases[i].operation==='boundary'?['boundary-prepare','boundary-move','territorial-edit']:['territory-components','territory-selection'];for(const operation of required)assert.ok(operations.includes(operation),'actual Worker operation '+operation);}
  if(suite.cases[i].id==='m975-annex-full-recursive'){const d=row.controls.delta;for(const field of ['file','recoveredStorage','recovered','full','fullStored'])verifyRawRecord(d[field]);assert.ok(d.changedIds.length&&d.removedIds.length);assert.equal(d.missingBaselineRejected,true);assert.equal(d.wrongBaselineRejected,true);const recovered=JSON.parse(d.recoveredStorage.raw),full=JSON.parse(d.fullStored.raw);assert.equal(Object.hasOwn(recovered,'physicalSourceInfo'),false,'delta does not carry environment source header');const {physicalSourceInfo,...fields}=full;assert.deepEqual(recovered,fields,'raw recovered fields differ only by explicitly absent environment source header');assert.deepEqual(d.sourceContext,physicalSourceInfo);assertExchangeEqual(JSON.parse(d.recovered.raw),JSON.parse(row.stages.redo.save.raw),'production resaved recovered delta');}
 }return rows;
}
export function verifyBrowserReport(suite,report){verifyExchangeSuite(suite);assert.equal(report.schema,'pando-m975-actual-chromium-model-exchange');assert.equal(report.version,1);assert.equal(report.state,'complete');assert.deepEqual(report.identity,suite.identity);assert.deepEqual(report.sourceHashes,Object.fromEntries(Object.entries(suite.sources).map(([k,v])=>[k,sha256(v)])));assert.deepEqual(report.evidenceHashes,Object.fromEntries(Object.entries(suite.evidenceSources).map(([k,v])=>[k,sha256(v)])));assert.equal(report.runtime.playwright,runtimePin.playwright);assert.equal(report.runtime.browserVersion,runtimePin.chromium);assert.equal(report.runtime.chromiumRevision,runtimePin.revision);assert.equal(report.runtime.cdp.jsVersion,runtimePin.v8);assert.ok(['Chrome/','HeadlessChrome/'].some(prefix=>report.runtime.cdp.product===prefix+runtimePin.chromium));verifyBrowserRows(suite,report.cases);return report;}
