#!/usr/bin/env python3
"""Deterministically generate the six-expression syntax bridge and V8 cosine closure.
--check never writes. Original vendor bytes and each expression count fail closed.
"""
from pathlib import Path
from hashlib import sha256
import argparse, json
ROOT = Path(__file__).resolve().parents[3]
RIVER = ROOT / 'assets/geometry/river'
PINS = {
 'river-territory-partition.js':'18b32eb7db238beaed99bce8bac980e547a48c785a7bd2071fa56fa63f51db24',
 'planar-graph-faces.js':'283da7701c21cb80e4fd9ef97e8f68e69a8d6f0ec9fc611ee8c23cab45d6c804',
}
replacements = [
 ("""items.push({
        ...candidate,
        countryId,
        polygonIndex,
        sourcePolygonIndex,
        componentKey,
        partitionKind: 'river',
      })""", """items.push(__riverOwnDataMerge({}, candidate, {
        countryId,
        polygonIndex,
        sourcePolygonIndex,
        componentKey,
        partitionKind: 'river',
      }))"""),
 ("{ ...component, countryId, polygonIndex, sourcePolygonIndex, componentKey, partitionKind: 'original' }", "__riverOwnDataMerge({}, component, { countryId, polygonIndex, sourcePolygonIndex, componentKey, partitionKind: 'original' })"),
 ("{ ...segment, a, b, bounds: null }", "__riverOwnDataMerge({}, segment, { a, b, bounds: null })"),
 ("{ ...face, riverEdges: face.edgeIds.filter(id => activeRiverEdges.has(id)) }", "__riverOwnDataMerge({}, face, { riverEdges: face.edgeIds.filter(id => activeRiverEdges.has(id)) })"),
 ("{ ...row, geometryKey, areaM2: metricGeometryArea(row.geometry, workspace) }", "__riverOwnDataMerge({}, row, { geometryKey, areaM2: metricGeometryArea(row.geometry, workspace) })"),
 ("{ ...RIVER_TERRITORY_PARTITION_CONFIG, ...(config || {}) }", "__riverOwnDataMerge({}, RIVER_TERRITORY_PARTITION_CONFIG, (config || {}))"),
]

def syntax(source):
    for before, after in replacements:
        if source.count(before) != 1: raise ValueError('RIVER_SYNTAX_COUNT_MISMATCH: ' + before)
        source = source.replace(before, after)
    return source

def generated():
    originals = {name:(RIVER/'original'/name).read_bytes() for name in PINS}
    for name, data in originals.items():
        if sha256(data).hexdigest() != PINS[name]: raise ValueError('RIVER_ORIGINAL_HASH_MISMATCH: ' + name)
    outputs = {RIVER/'adapted/river-territory-partition.js':syntax(originals['river-territory-partition.js'].decode()).encode(),
               RIVER/'adapted/planar-graph-faces.js':originals['planar-graph-faces.js']}
    vendor=ROOT/'app/river/vendor'
    data=(vendor/'ieee754.cc').read_bytes()
    source_hash='1bf999809d4c4c1d31ad5ff3578d32614796f159e08b9e7782560d017721a0c2'
    if sha256(data).hexdigest()!=source_hash: raise ValueError('V8_SOURCE_HASH_MISMATCH')
    license_hash='6ab33af8774a0f396ee3aeeb761e3229057682d6f9fa7f572e390c2cb3a6e509'
    if sha256((vendor/'LICENSE.v8').read_bytes()).hexdigest()!=license_hash: raise ValueError('V8_LICENSE_HASH_MISMATCH')
    source=data.decode()
    notice=source[:source.index('#include')]
    helpers=source[source.index('namespace v8 {'):source.index('/* __kernel_tan(')]
    cosine=source[source.index('#if defined(V8_USE_LIBM_TRIG_FUNCTIONS)'):source.index('/* exp(x)')]
    if helpers.count('V8_INLINE double __kernel_cos')!=1 or helpers.count('V8_INLINE double __kernel_sin')!=1 or cosine.count('double cos(double x)')!=1:
        raise ValueError('V8_EXTRACTION_MISMATCH')
    closure=notice+'// Mechanically generated by tools/m97/river/generate-adapters.py; do not edit.\n#include <bit>\n#include <cmath>\n#include <cstdint>\n#if defined(_MSC_VER)\n#define V8_CC_MSVC 1\n#else\n#define V8_CC_MSVC 0\n#endif\n#define V8_WARN_UNUSED_RESULT\n#define V8_INLINE inline\nnamespace v8 { namespace base { using std::bit_cast; } }\n'+helpers+'\n} // anonymous namespace\n'+cosine+'\n} } } // v8::base::ieee754\nextern double riverV8Cos(double x) { return v8::base::ieee754::cos(x); }\n'
    outputs[ROOT/'app/river/v8-cosine.cpp']=closure.encode()
    manifest={'webCommit':'53dbd3c1e84f04cf0332adc1b7a32f290b2a4f47','originalSha256':PINS,
      'syntaxReplacements':[{'before':a,'after':b} for a,b in replacements],
      'generatedSha256':{str(path.relative_to(ROOT)):sha256(data).hexdigest() for path,data in outputs.items()},
      'cosine':{'source':'https://raw.githubusercontent.com/nodejs/node/v24.19.0/deps/v8/src/base/ieee754.cc','sourceSha256':source_hash,
        'license':'https://raw.githubusercontent.com/nodejs/node/v24.19.0/deps/v8/LICENSE','licenseSha256':license_hash,
        'extraction':'Unchanged helper and cosine bodies; standard C++20 bit_cast and macro scaffolding only.',
        'compiler':'Source-isolated no-fast-math and no FP contraction (MSVC /fp:strict).'}}
    outputs[RIVER/'provenance.json']=(json.dumps(manifest,indent=2)+'\n').encode()
    return outputs

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,data in generated().items():
        if args.check:
            if not path.is_file() or path.read_bytes()!=data: raise SystemExit('GENERATED_DRIFT: '+str(path))
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
    print('Verified guarded original sources, six replacements, unchanged planar module, and official V8 cosine closure.')
