import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const api=await import('./m974-native-source-order.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});
const hash=b=>createHash('sha256').update(b).digest('hex');
function pair(){
 const geometry={type:'Polygon',coordinates:[[[0,0],[0,2],[2,2],[2,0],[0,0]]]},sources=['a','b'].map(id=>({id,geometry:structuredClone(geometry)}));
 const document={format:'pandoeditor-project',version:9,units:sources.map(({id})=>({id,kind:'general'})),timelineRecords:{geometryBindings:sources.map(({id})=>({entityId:id,validFrom:null,validTo:null,geometryRef:{id,version:1}}))},geometries:sources.map(({id,geometry})=>({id,version:1,geojson:geometry}))};
 const bytes=Buffer.from(JSON.stringify(document)),indicator=id=>({kind:'vertex',coordinate:[0,0],ownerIds:[id],nodeKey:'0.0000000,0.0000000',segmentKey:null,segmentEndpoints:null});
 const web={case:'source-order-v2-coincident-remove-restore-a',input:{features:sources.map(s=>({...s,type:'Feature'})),query:{coordinate:[0,0]}},stages:{warm:{candidates:[indicator('a')],firstCandidateOwnerIds:['a']},afterRestore:{candidates:[indicator('b')],firstCandidateOwnerIds:['b']}}};
 const native={schema:'pando-m974-native-controller-source-order',version:1,case:web.case,scope:'native-controller-delete-undo',sourceGeometries:sources,restoredSourceGeometries:structuredClone(sources),warm:{indicator:indicator('a')},afterRestore:{indicator:indicator('b')},transitions:{deleteStarted:true,deleteApplied:true,undoAvailable:true,undoApplied:true,revisionBefore:0,revisionAfterDelete:1,revisionAfterUndo:2,submittedBeforeDelete:1,submittedAfterUndo:1},canonicalEqualAfterUndo:true,beforeDocumentSha256:hash(bytes),afterDocumentSha256:hash(bytes),beforeDocumentBytesBase64:bytes.toString('base64'),afterDocumentBytesBase64:bytes.toString('base64')};return [web,native];
}
test('source-order comparison preserves separate stimulus layers',()=>{assert.equal(typeof api.compareSourceOrder,'function');const r=api.compareSourceOrder(...pair());assert.equal(r.passed,true);assert.equal(r.rawParity,false);assert.equal(r.fullWebUndoParity,false);});
test('wrong winner coordinate and missing values fail closed',()=>{for(const mutate of [n=>n.afterRestore.indicator.ownerIds=['a'],n=>n.afterRestore.indicator.coordinate=[Number.MIN_VALUE,0],n=>delete n.warm,n=>delete n.transitions.undoApplied,n=>n.transitions.submittedAfterUndo=2]){const [w,n]=pair();mutate(n);assert.equal(api.compareSourceOrder(w,n).passed,false);}});
test('native canonical bytes authenticate both hash and source geometry',()=>{for(const mutate of [n=>n.beforeDocumentBytesBase64+='!',n=>n.afterDocumentSha256='0'.repeat(64),n=>n.sourceGeometries[0].geometry.coordinates[0][1][0]=1,n=>n.restoredSourceGeometries.reverse()]){const [w,n]=pair();mutate(n);assert.equal(api.compareSourceOrder(w,n).passed,false);}});
test('unknown exclusions and schema versions are rejected',()=>{for(const mutate of [n=>n.exclusions=['winner'],n=>n.version=2,n=>n.case='other']){const [w,n]=pair();mutate(n);assert.equal(api.compareSourceOrder(w,n).passed,false);}});
test('CLI requires exact identities and rejects ambiguous options',()=>{assert.equal(typeof api.parseArguments,'function');for(const args of [[],['--unknown','x'],['--expected-run-id','1','--expected-run-id','2']])assert.throws(()=>api.parseArguments(args));});
test('artifact identity rejects stale same-commit runs and missing identity',()=>{assert.equal(typeof api.verifyIdentity,'function');const expected={expectedCommit:'a'.repeat(40),expectedRunId:'123'},suite={commit:expected.expectedCommit,runId:'123',identity:{commit:expected.expectedCommit,runId:'123'}},report={identity:{...suite.identity}};api.verifyIdentity(suite,report,expected);assert.throws(()=>api.verifyIdentity(suite,report,{...expected,expectedRunId:'124'}));assert.throws(()=>api.verifyIdentity(suite,{identity:{}},expected));});
